<?php

declare(strict_types=1);

namespace Modules\Directory\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Directory\Models\Category;
use Modules\Directory\Models\Tool;

class DirectoryNewToolsSeeder extends Seeder
{
    public function run(): void
    {
        $category = Category::first();

        $tools = [
            ['name' => 'Notion AI', 'slug' => 'notion-ai', 'url' => 'https://notion.so', 'pricing' => 'freemium', 'launch_year' => 2023, 'short_description' => "L'intelligence artificielle directement intégrée dans votre espace de travail Notion.", 'description' => "Notion AI vous aide à écrire, résumer et générer du contenu sans jamais quitter vos notes. C'est l'outil parfait pour nettoyer vos brouillons ou brainstormer des idées rapidement.", 'how_to_use' => "Ouvrez une page Notion, appuyez sur la barre d'espace et demandez à l'IA de rédiger ou de résumer du texte.", 'core_features' => 'Rédaction assistée, Résumé automatique, Traduction, Amélioration du style, Génération de tableaux', 'use_cases' => 'Prise de notes, Gestion de projet, Rédaction de blog, Documentation technique', 'pros' => 'Intégration fluide, Gain de temps énorme, Interface familière', 'cons' => "Payant pour l'illimité, Moins puissant que GPT-4 seul", 'target_audience' => ['Étudiants', 'Gestionnaires', 'Équipes produit'], 'faq' => [['question' => 'Est-ce que Notion AI est gratuit ?', 'answer' => "Il y a un essai gratuit limité, mais c'est un ajout payant par la suite."], ['question' => 'Peut-il traduire mes documents ?', 'answer' => 'Oui, il traduit très bien dans plusieurs langues, incluant le français.']]],
            ['name' => 'Canva AI', 'slug' => 'canva-ai', 'url' => 'https://canva.com', 'pricing' => 'freemium', 'launch_year' => 2023, 'short_description' => 'La suite magique de Canva pour créer des visuels en quelques clics.', 'description' => "Canva intègre l'IA pour générer des images, effacer des objets ou étendre des arrière-plans automatiquement. Idéal pour ceux qui veulent de beaux designs sans être graphistes.", 'how_to_use' => "Dans l'éditeur, cliquez sur \"Édition magique\" et décrivez ce que vous voulez voir apparaître.", 'core_features' => 'Texte en image, Gomme magique, Expansion magique, Édition vidéo, Traduction de design', 'use_cases' => 'Réseaux sociaux, Présentations, Marketing, Création de logos', 'pros' => 'Super intuitif, Tout-en-un, Résultats rapides', 'cons' => 'Moins réaliste que Midjourney, Nécessite un compte Pro pour tout', 'target_audience' => ['Marketeurs', 'Entrepreneurs', 'Créateurs de contenu'], 'faq' => [['question' => 'Faut-il savoir dessiner ?', 'answer' => 'Pas du tout, vous écrivez ce que vous voulez et Canva le génère.'], ['question' => 'Les images sont-elles libres de droits ?', 'answer' => 'Oui, vous pouvez les utiliser pour vos projets commerciaux.']]],
            ['name' => 'Suno', 'slug' => 'suno', 'url' => 'https://suno.com', 'pricing' => 'freemium', 'launch_year' => 2023, 'short_description' => 'Créez des chansons complètes avec paroles et voix juste avec du texte.', 'description' => "Suno est capable de composer une chanson de A à Z, incluant la mélodie et les paroles, dans n'importe quel style musical.", 'how_to_use' => 'Inscrivez-vous, décrivez le style de musique et le sujet, puis cliquez sur Créer.', 'core_features' => 'Génération de chansons, Écriture de paroles, Styles variés, Voix réalistes, Mode instrumental', 'use_cases' => 'Divertissement, Jingles publicitaires, Prototypage musical, Cadeaux personnalisés', 'pros' => 'Qualité audio impressionnante, Très facile à utiliser, Rapide', 'cons' => "Contrôle limité sur la mélodie, Droits d'auteur flous en version gratuite", 'target_audience' => ['Musiciens amateurs', 'Créateurs de contenu', 'Grand public'], 'faq' => [['question' => 'Puis-je vendre les chansons ?', 'answer' => "Seulement si vous avez un abonnement payant au moment de la création."], ['question' => 'Est-ce que ça chante en français ?', 'answer' => 'Oui, et même avec un accent si vous le spécifiez bien.']]],
            ['name' => 'ElevenLabs', 'slug' => 'elevenlabs', 'url' => 'https://elevenlabs.io', 'pricing' => 'freemium', 'launch_year' => 2022, 'short_description' => 'Le meilleur outil de synthèse vocale et de clonage de voix.', 'description' => "ElevenLabs génère des voix ultra-réalistes à partir de texte. Vous pouvez même cloner votre propre voix pour lire du contenu automatiquement.", 'how_to_use' => 'Tapez votre texte, choisissez une voix ou téléversez un échantillon audio pour cloner une voix.', 'core_features' => 'Synthèse vocale, Clonage de voix, Doublage vidéo, Bibliothèque de voix, Support multilingue', 'use_cases' => 'Livres audio, Vidéos YouTube, Jeux vidéo, Accessibilité', 'pros' => 'Réalisme époustouflant, Beaucoup de langues, Clonage précis', 'cons' => 'Crédits limités en gratuit, Peut être dispendieux pour les gros volumes', 'target_audience' => ['Podcasteurs', 'Développeurs de jeux', 'Youtubers'], 'faq' => [['question' => 'Est-ce que ça sonne robotique ?', 'answer' => "Non, c'est l'une des IA les plus naturelles sur le marché."], ['question' => 'Puis-je utiliser ma propre voix ?', 'answer' => 'Oui, la fonction de clonage instantané permet de le faire facilement.']]],
            ['name' => 'Runway', 'slug' => 'runway', 'url' => 'https://runwayml.com', 'pricing' => 'freemium', 'launch_year' => 2022, 'short_description' => "Une suite créative pour générer et éditer des vidéos avec l'IA.", 'description' => "Runway est un pionnier dans la génération de vidéo. Il permet de transformer du texte en vidéo ou de modifier des séquences existantes.", 'how_to_use' => 'Allez dans "Text to Video", décrivez une scène cinématique et laissez l\'IA générer le clip.', 'core_features' => 'Gen-3 Alpha, Texte vers vidéo, Image vers vidéo, Inpainting, Ralenti fluide', 'use_cases' => 'Cinéma, Publicité, Clips musicaux, Effets visuels', 'pros' => "Technologie de pointe, Contrôle créatif, Outils d'édition complets", 'cons' => "Courbe d'apprentissage, Génération vidéo coûteuse en crédits", 'target_audience' => ['Artistes visuels', 'Monteurs vidéo', 'Agences de pub'], 'faq' => [['question' => 'Quelle est la durée des vidéos ?', 'answer' => 'Généralement quelques secondes, mais vous pouvez les étendre.'], ['question' => 'Est-ce accessible aux débutants ?', 'answer' => 'Oui, mais maîtriser les prompts demande de la pratique.']]],
            ['name' => 'Copilot', 'slug' => 'copilot', 'url' => 'https://copilot.microsoft.com', 'pricing' => 'freemium', 'launch_year' => 2023, 'short_description' => "L'assistant IA de Microsoft pour le web et la bureautique.", 'description' => "Basé sur GPT-4, Copilot s'intègre à Windows et au web pour répondre à vos questions, générer des images et vous aider. C'est un assistant polyvalent et gratuit.", 'how_to_use' => 'Connectez-vous avec un compte Microsoft et posez vos questions dans la barre latérale de Edge ou sur le site.', 'core_features' => "Recherche web, Génération d'images (DALL-E 3), Résumé de pages, Rédaction de courriels, Code", 'use_cases' => "Recherche d'info, Productivité bureau, Apprentissage, Programmation", 'pros' => 'Accès gratuit à GPT-4, Connecté à Internet, Intégré à Office', 'cons' => 'Parfois lent, Filtres de contenu stricts', 'target_audience' => ['Employés de bureau', 'Étudiants', 'Développeurs'], 'faq' => [['question' => 'Est-ce la même chose que ChatGPT ?', 'answer' => "C'est similaire, mais Copilot est connecté au web en temps réel par défaut."], ['question' => 'Est-ce gratuit ?', 'answer' => "La version web est gratuite, l'intégration Office 365 est payante."]]],
            ['name' => 'NotebookLM', 'slug' => 'notebooklm', 'url' => 'https://notebooklm.google', 'pricing' => 'free', 'launch_year' => 2023, 'short_description' => 'Un carnet de notes intelligent par Google pour analyser vos documents.', 'description' => "NotebookLM vous permet de discuter avec vos propres PDF et notes. Il peut même générer un podcast audio où deux IA débattent de votre contenu.", 'how_to_use' => 'Importez vos PDF ou Google Docs, puis posez des questions sur le contenu ou cliquez sur Audio Overview.', 'core_features' => 'Analyse de documents, Citations de sources, Audio Overview, Résumés, FAQ automatique', 'use_cases' => 'Étude, Recherche académique, Analyse de rapports, Préparation de réunions', 'pros' => 'Hallucine très peu, Totalement gratuit, Fonction audio virale', 'cons' => 'Limité à vos documents, Encore expérimental', 'target_audience' => ['Chercheurs', 'Étudiants universitaires', 'Journalistes'], 'faq' => [['question' => "Mes données servent-elles à entraîner l'IA ?", 'answer' => 'Google affirme que les données dans NotebookLM restent privées.'], ['question' => 'Le podcast audio est-il en français ?', 'answer' => "L'audio est en anglais pour l'instant, mais le texte fonctionne en français."]]],
            ['name' => 'v0', 'slug' => 'v0', 'url' => 'https://v0.dev', 'pricing' => 'freemium', 'launch_year' => 2024, 'short_description' => "Générez des interfaces utilisateur React et Tailwind juste en décrivant votre idée.", 'description' => "Créé par Vercel, v0 transforme vos descriptions textuelles en code propre React. C'est un outil incroyable pour prototyper des interfaces web rapidement.", 'how_to_use' => 'Décrivez l\'interface souhaitée et copiez le code généré directement.', 'core_features' => 'Génération UI, React + Tailwind, Itération par chat, Export de code, Prévisualisation', 'use_cases' => 'Prototypage, Création de dashboards, Composants web, MVP', 'pros' => 'Code de haute qualité, Gain de temps frontend, Moderne', 'cons' => "Nécessite des connaissances techniques, Parfois répétitif", 'target_audience' => ['Développeurs Frontend', 'Designers UI', 'Fondateurs techniques'], 'faq' => [['question' => 'Est-ce que le code est propre ?', 'answer' => "Oui, c'est surprenamment propre et utilise des bonnes pratiques modernes."], ['question' => "Puis-je l'utiliser pour un site complet ?", 'answer' => "C'est mieux pour des composants ou des pages uniques."]]],
            ['name' => 'Bolt', 'slug' => 'bolt', 'url' => 'https://bolt.new', 'pricing' => 'freemium', 'launch_year' => 2024, 'short_description' => 'Développez et déployez des applications web complètes dans le navigateur.', 'description' => "Bolt crée, exécute et déploie des applications Full Stack sans aucune configuration locale. C'est magique pour tester des idées rapidement.", 'how_to_use' => 'Allez sur bolt.new, décrivez votre app et regardez-le coder en temps réel.', 'core_features' => "Environnement de dev complet, Installation npm, Déploiement instantané, Édition de code, Chat contextuel", 'use_cases' => 'Hackathons, Démarrage de projets, Apprentissage du code, Outils internes', 'pros' => 'Rien à installer, Très rapide, Gère le backend et frontend', 'cons' => 'Peut bloquer sur des apps très complexes, Limites en gratuit', 'target_audience' => ['Développeurs Fullstack', 'Entrepreneurs', 'Débutants en code'], 'faq' => [['question' => 'Faut-il installer VS Code ?', 'answer' => 'Non, tout se passe dans votre navigateur web.'], ['question' => 'Peut-on exporter le projet ?', 'answer' => 'Oui, vous pouvez télécharger les fichiers ou déployer sur Netlify.']]],
            ['name' => 'Lovable', 'slug' => 'lovable', 'url' => 'https://lovable.dev', 'pricing' => 'freemium', 'launch_year' => 2024, 'short_description' => 'Transformez vos idées en logiciels fonctionnels sans toucher au code.', 'description' => "Lovable se positionne comme un ingénieur logiciel autonome. Il permet de bâtir des apps complexes via une conversation.", 'how_to_use' => 'Décrivez la fonctionnalité désirée et Lovable écrit et commite le code pour vous.', 'core_features' => 'Développement autonome, Intégration GitHub, Supabase intégré, UI/UX soigné, Itération rapide', 'use_cases' => 'Lancement de SaaS, Outils métiers, Prototypes avancés', 'pros' => 'Interface très léchée, Comprend bien le contexte, Rapide', 'cons' => "Encore jeune, Dépendance à l'IA pour la maintenance", 'target_audience' => ['Fondateurs non-techniques', 'Product Managers', 'Développeurs pressés'], 'faq' => [['question' => "Est-ce vraiment No-code ?", 'answer' => "Vous n'avez pas besoin d'écrire de code, mais comprendre la logique aide."], ['question' => 'Quelle technologie est utilisée ?', 'answer' => 'Principalement React, Tailwind et Supabase pour le backend.']]],
            ['name' => 'Gamma', 'slug' => 'gamma', 'url' => 'https://gamma.app', 'pricing' => 'freemium', 'launch_year' => 2023, 'short_description' => 'Créez des présentations et documents magnifiques en quelques secondes.', 'description' => "Oubliez PowerPoint. Gamma génère des diapositives visuelles et structurées à partir d'un simple titre ou de vos notes.", 'how_to_use' => 'Choisissez "Présentation", entrez votre sujet et Gamma génère toutes les slides automatiquement.', 'core_features' => "Génération de decks, Mise en page flexible, Intégration d'images, Mode document, Export PDF/PPT", 'use_cases' => 'Pitch decks, Rapports mensuels, Cours en ligne, Portfolios', 'pros' => 'Design toujours beau, Gain de temps phénoménal, Interactif', 'cons' => 'Moins de contrôle pixel-perfect, Export PPT parfois rigide', 'target_audience' => ['Consultants', 'Étudiants', 'Commerciaux'], 'faq' => [['question' => 'Puis-je modifier le texte après ?', 'answer' => "Oui, c'est un éditeur complet comme Google Slides mais plus simple."], ['question' => 'Est-ce compatible avec PowerPoint ?', 'answer' => 'Oui, vous pouvez exporter au format .pptx.']]],
            ['name' => 'Napkin AI', 'slug' => 'napkin-ai', 'url' => 'https://napkin.ai', 'pricing' => 'freemium', 'launch_year' => 2024, 'short_description' => "L'outil idéal pour illustrer vos documents avec des visuels simples.", 'description' => "Napkin AI analyse votre texte et suggère automatiquement des diagrammes ou des croquis pour rendre vos écrits plus digestes.", 'how_to_use' => 'Collez votre texte dans Napkin, cliquez sur les paragraphes et choisissez parmi les visuels suggérés.', 'core_features' => 'Visualisation de texte, Diagrammes automatiques, Style esquisse, Édition de graphiques, Export PNG/SVG', 'use_cases' => 'Documentation technique, Articles de blog, Présentations, Manuels', 'pros' => 'Rend le texte vivant, Style visuel unique, Très simple', 'cons' => 'En bêta, Choix de styles encore limité', 'target_audience' => ['Rédacteurs techniques', 'Blogueurs', 'Enseignants'], 'faq' => [['question' => "Est-ce que ça remplace un graphiste ?", 'answer' => 'Pour des schémas explicatifs simples, absolument.'], ['question' => 'Puis-je exporter vers Google Docs ?', 'answer' => 'Oui, via extension ou copier-coller des images.']]],
            ['name' => 'Leonardo AI', 'slug' => 'leonardo-ai', 'url' => 'https://leonardo.ai', 'pricing' => 'freemium', 'launch_year' => 2022, 'short_description' => "Une plateforme de génération d'images artistiques avec un contrôle précis.", 'description' => "Leonardo est reconnu pour la qualité artistique de ses modèles et ses outils avancés pour les créateurs de jeux et d'art.", 'how_to_use' => 'Sélectionnez un modèle, tapez votre prompt et utilisez les réglages pour ajuster le style.', 'core_features' => 'Modèles finetunés, Canvas Editor, Génération de textures, Alchemy Refiner, Upscaling', 'use_cases' => 'Assets de jeux vidéo, Concept art, Illustrations, Design de mode', 'pros' => 'Interface web complète, Modèles spécifiques, Crédits quotidiens gratuits', 'cons' => 'Interface chargée pour les débutants, Beaucoup de paramètres', 'target_audience' => ['Game Designers', 'Artistes digitaux', 'Illustrateurs'], 'faq' => [['question' => 'Est-ce mieux que Midjourney ?', 'answer' => "C'est différent : plus de contrôle et une interface web, mais un style distinct."], ['question' => "Les images m'appartiennent-elles ?", 'answer' => 'Oui, vous possédez les droits commerciaux des images générées.']]],
            ['name' => 'HeyGen', 'slug' => 'heygen', 'url' => 'https://heygen.com', 'pricing' => 'paid', 'launch_year' => 2022, 'short_description' => 'Créez des vidéos professionnelles avec des avatars IA qui parlent.', 'description' => "HeyGen permet de faire parler un avatar virtuel avec une synchronisation labiale parfaite. Idéal pour faire des vidéos de formation sans caméra.", 'how_to_use' => 'Choisissez un avatar, tapez votre script, sélectionnez une voix et générez la vidéo.', 'core_features' => "Avatars réalistes, Lip-sync, Traduction vidéo, Clonage d'avatar, Modèles de vidéo", 'use_cases' => 'Formation, Marketing, Service client, Vidéos de vente', 'pros' => 'Résultat très pro, Traduction vidéo bluffante, Facile', 'cons' => 'Assez dispendieux, Pas de version gratuite illimitée', 'target_audience' => ['Entreprises', 'Formateurs', 'Équipes marketing'], 'faq' => [['question' => 'Puis-je créer mon propre avatar ?', 'answer' => 'Oui, vous pouvez vous filmer 2 minutes pour créer votre jumeau numérique.'], ['question' => 'Est-ce que ça marche en français ?', 'answer' => 'Oui, la synchronisation des lèvres fonctionne parfaitement en français.']]],
            ['name' => 'Ideogram AI', 'slug' => 'ideogram-ai', 'url' => 'https://ideogram.ai', 'pricing' => 'freemium', 'launch_year' => 2024, 'short_description' => "Le générateur d'images spécialiste du texte et de la typographie.", 'description' => "Là où d'autres échouent à écrire du texte dans les images, Ideogram excelle. Parfait pour créer des logos ou des affiches avec du texte lisible.", 'how_to_use' => 'Décrivez l\'image et mettez le texte voulu entre guillemets dans votre prompt.', 'core_features' => 'Rendu de texte précis, Styles typographiques, Logos, Affiches, Magic Prompt', 'use_cases' => 'Design de logo, Print on demand, Affiches événementielles, Stickers', 'pros' => 'Le meilleur pour le texte, Très créatif, Simple', 'cons' => "Moins photoréaliste que d'autres, Résolution parfois limitée", 'target_audience' => ['Graphistes', 'Vendeurs Etsy', 'Designers de marque'], 'faq' => [['question' => 'Le texte est-il toujours correct ?', 'answer' => "C'est beaucoup mieux que la concurrence, mais il faut parfois s'y reprendre."], ['question' => 'Est-ce gratuit ?', 'answer' => 'Il y a un plan gratuit généreux avec un nombre limité de générations par jour.']]],
        ];

        foreach ($tools as $index => $data) {
            $tool = Tool::firstOrCreate(
                ['slug->fr_CA' => $data['slug']],
                ['name' => json_encode(['fr_CA' => $data['name']]), 'url' => $data['url'], 'pricing' => $data['pricing'], 'status' => 'published', 'sort_order' => 10 + $index, 'website_type' => 'website', 'launch_year' => $data['launch_year'], 'target_audience' => $data['target_audience'], 'faq' => $data['faq']]
            );

            $tool->setTranslation('name', 'fr_CA', $data['name']);
            $tool->setTranslation('slug', 'fr_CA', $data['slug']);
            $tool->setTranslation('description', 'fr_CA', $data['description']);
            $tool->setTranslation('short_description', 'fr_CA', $data['short_description']);
            $tool->setTranslation('how_to_use', 'fr_CA', $data['how_to_use']);
            $tool->setTranslation('core_features', 'fr_CA', $data['core_features']);
            $tool->setTranslation('use_cases', 'fr_CA', $data['use_cases']);
            $tool->setTranslation('pros', 'fr_CA', $data['pros']);
            $tool->setTranslation('cons', 'fr_CA', $data['cons']);
            $tool->save();

            if ($category) {
                $tool->categories()->syncWithoutDetaching([$category->id]);
            }
        }
    }
}
