<?php

declare(strict_types=1);

namespace Modules\Dictionary\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Modules\Dictionary\Models\Category;
use Modules\Dictionary\Models\Term;

class DictionaryPromptingSeeder extends Seeder
{
    public function run(): void
    {
        $catIds = [];
        foreach (['Outils et techniques' => 'outils'] as $name => $key) {
            $cat = Category::whereRaw("JSON_EXTRACT(name, '$.fr_CA') = ?", ['"'.$name.'"'])->first();
            if ($cat) {
                $catIds[$key] = $cat->id;
            }
        }

        $terms = [
            ['name' => 'ReAct (Reason + Act)', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '⚛️', 'cat' => 'outils', 'definition' => "Technique combinant raisonnement et action permettant à l'IA de planifier ses étapes puis d'interagir avec des outils externes pour exécuter des tâches complexes.", 'analogy' => "C'est comme un plombier qui réfléchit au problème (raison) avant de prendre sa clé anglaise (action), puis ajuste son plan au fur et à mesure.", 'example' => "Pour répondre à « Quel est le meilleur restaurant près de mon hôtel à Paris\u{00A0}? », l'IA raisonne, cherche la météo, puis utilise cette info pour trouver un restaurant avec terrasse.", 'fact' => 'ReAct est devenu le standard pour les agents IA autonomes en 2025-2026, utilisé par ChatGPT, Claude et Gemini pour interagir avec des outils.'],
            ['name' => 'Self-consistency', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🎯', 'cat' => 'outils', 'definition' => 'Technique qui génère plusieurs raisonnements différents pour une même question, puis sélectionne la réponse la plus fréquente par vote majoritaire.', 'analogy' => "C'est comme demander à 5 amis de résoudre un problème de math séparément, puis prendre la réponse sur laquelle la majorité s'entend.", 'example' => "Pour un problème de logique, l'IA génère 10 chaînes de pensée différentes et choisit la réponse qui revient 7 fois sur 10.", 'fact' => "Cette technique réduit les hallucinations de 15 à 25\u{00A0}% sur les tâches de raisonnement mathématique et logique."],
            ['name' => 'Tree-of-thought', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🌳', 'cat' => 'outils', 'definition' => "Explore plusieurs chemins de raisonnement possibles sous forme d'arborescence, permettant des retours en arrière et des évaluations de chaque branche.", 'analogy' => "C'est comme un joueur d'échecs qui visualise plusieurs coups possibles et leurs conséquences avant de déplacer sa pièce.", 'example' => "Pour résoudre un casse-tête créatif comme écrire un poème avec des contraintes, l'IA explore différentes directions et garde les meilleures.", 'fact' => "Tree-of-thought dépasse les approches linéaires en autorisant l'exploration parallèle, comme le fait le cerveau humain."],
            ['name' => 'Emotion prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '💖', 'cat' => 'outils', 'definition' => "Technique ajoutant une charge émotionnelle ou cognitive au prompt pour améliorer la précision et l'engagement des réponses de l'IA.", 'analogy' => "C'est comme dire à un étudiant « cet examen est très important pour ta carrière » – la pression émotionnelle le pousse à mieux performer.", 'example' => "Ajouter « C'est très important pour mon travail, sois le plus précis possible » à la fin d'un prompt augmente la qualité de la réponse.", 'fact' => "Validée par Microsoft et Google en 2024, cette technique améliore la précision des réponses de 15 à 40\u{00A0}% selon les tâches."],
            ['name' => 'APE (Automatic Prompt Engineer)', 'type' => 'acronym', 'difficulty' => 'advanced', 'icon' => '🤖', 'cat' => 'outils', 'definition' => "Système où l'IA génère et optimise automatiquement ses propres prompts pour accomplir une tâche donnée, sans intervention humaine.", 'analogy' => "C'est comme un cuisinier qui ajuste sa recette tout seul à force d'essais jusqu'à trouver le goût parfait.", 'example' => "APE peut créer automatiquement le prompt optimal pour qu'une IA génère des descriptions de produits efficaces pour un site de commerce.", 'fact' => 'APE a démontré sa capacité à générer des prompts plus performants que ceux créés manuellement par des experts humains.'],
            ['name' => 'Self-refine', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🔄', 'cat' => 'outils', 'definition' => "L'IA génère une première réponse, l'évalue elle-même, identifie les faiblesses et l'améliore itérativement sans intervention humaine.", 'analogy' => "C'est comme relire ta dissertation trois fois en corrigeant les fautes et en améliorant les phrases à chaque passage.", 'example' => "L'IA écrit un courriel professionnel, le relit, trouve le ton trop familier, et le reformule de manière plus formelle.", 'fact' => "Self-refine permet d'atteindre une qualité proche de la révision humaine en seulement 2 à 3 itérations automatiques."],
            ['name' => 'Reflexion', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🪞', 'cat' => 'outils', 'definition' => "Technique où l'IA simule une réflexion métacognitive sur ses erreurs passées pour corriger son raisonnement dans les tentatives suivantes.", 'analogy' => "C'est comme un joueur de hockey qui révisionne ses parties pour identifier ses erreurs et s'améliorer au prochain match.", 'example' => "Après avoir échoué à résoudre un problème de code, l'IA analyse ce qui n'a pas fonctionné et ajuste sa stratégie.", 'fact' => "La réflexion peut améliorer les performances de l'IA de 50 à 75\u{00A0}% sur des tâches de raisonnement complexe."],
            ['name' => 'Chain-of-verification', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '✅', 'cat' => 'outils', 'definition' => "Méthode où l'IA génère une réponse, puis crée des questions de vérification pour confirmer l'exactitude de chaque affirmation.", 'analogy' => "C'est comme un journaliste qui vérifie ses sources avant de publier un article – chaque fait est validé indépendamment.", 'example' => "Après avoir généré une biographie, l'IA pose des questions comme « Est-ce que cette date de naissance est correcte\u{00A0}? » et corrige si nécessaire.", 'fact' => 'Technique cruciale pour réduire les hallucinations, surtout pour les contenus factuels et les données sensibles.'],
            ['name' => 'Step-back prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🔭', 'cat' => 'outils', 'definition' => "Demande à l'IA de prendre du recul et de considérer les principes généraux avant de répondre à une question spécifique.", 'analogy' => "C'est comme regarder la carte du Québec en entier avant de zoomer sur ton quartier pour trouver un chemin.", 'example' => "Au lieu de répondre directement à « Pourquoi le ciel est bleu\u{00A0}? », l'IA réfléchit d'abord aux principes de la diffusion de la lumière.", 'fact' => 'Cette technique améliore significativement la qualité des réponses sur les questions scientifiques et techniques complexes.'],
            ['name' => 'Least-to-most prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🪜', 'cat' => 'outils', 'definition' => 'Décompose un problème complexe en sous-problèmes du plus simple au plus difficile, les résolvant séquentiellement de façon cumulative.', 'analogy' => "C'est comme monter un escalier marche par marche au lieu d'essayer de sauter directement en haut.", 'example' => "Pour traduire un texte technique, l'IA traduit d'abord les mots clés, puis les phrases simples, puis les paragraphes complexes.", 'fact' => "Cette approche pédagogique aide l'IA à mieux gérer la complexité et réduit les erreurs sur les problèmes à plusieurs étapes."],
            ['name' => 'Role prompting', 'type' => 'ai_term', 'difficulty' => 'beginner', 'icon' => '🎭', 'cat' => 'outils', 'definition' => "Technique attribuant un rôle spécifique à l'IA (expert, professeur, avocat) pour adapter sa voix, son ton et son expertise à un contexte précis.", 'analogy' => "C'est comme demander à un acteur de jouer un personnage – il adapte tout son comportement au rôle.", 'example' => "Dire à ChatGPT « Tu es un nutritionniste expérimenté » avant de poser des questions sur l'alimentation.", 'fact' => "C'est la technique de prompting la plus utilisée au quotidien, souvent sans que les utilisateurs s'en rendent compte."],
            ['name' => 'Meta-prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🧩', 'cat' => 'outils', 'definition' => "Technique qui utilise des prompts pour générer ou améliorer d'autres prompts, optimisant ainsi la communication avec l'IA.", 'analogy' => "C'est comme écrire un mode d'emploi pour rédiger de meilleurs modes d'emploi – tu améliores le processus lui-même.", 'example' => "Demander à l'IA « Crée le meilleur prompt possible pour générer des logos minimalistes avec DALL-E ».", 'fact' => 'Le meta-prompting est à la base des outils comme APE et des « prompt generators » qui automatisent la création de prompts.'],
            ['name' => 'Graph-of-thought', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🕸️', 'cat' => 'outils', 'definition' => "Modélise le raisonnement de l'IA comme un graphe non linéaire où les idées sont interconnectées, dépassant les limites de l'arbre de pensée.", 'analogy' => "C'est comme une carte mentale où chaque idée est reliée à plusieurs autres, formant un réseau de connexions.", 'example' => "Pour planifier un voyage complexe, l'IA connecte les contraintes de budget, météo, activités et transport dans un réseau de décisions.", 'fact' => 'Extension du Tree-of-thought, le Graph-of-thought permet de modéliser des problèmes où les éléments sont interdépendants.'],
            ['name' => 'Skeleton-of-thought', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🦴', 'cat' => 'outils', 'definition' => "L'IA génère d'abord un squelette structurel de la réponse (plan, titres), puis remplit chaque section en parallèle pour accélérer la génération.", 'analogy' => "C'est comme dessiner les contours d'une maison avant de construire les murs et poser le toit.", 'example' => "Pour rédiger un article de blogue, l'IA crée d'abord les 5 titres de sections, puis écrit le contenu de chacune simultanément.", 'fact' => 'Cette technique peut accélérer la génération de contenu de 2 à 3 fois tout en améliorant la cohérence globale.'],
            ['name' => 'Program-of-thought', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '💻', 'cat' => 'outils', 'definition' => "L'IA exprime son raisonnement sous forme de code exécutable (Python, JavaScript) qui peut être vérifié automatiquement.", 'analogy' => "C'est comme écrire un programme pour calculer tes impôts au lieu de le faire à la main – le code ne se trompe pas.", 'example' => "Pour des calculs financiers complexes, l'IA génère un script Python qui effectue les opérations et retourne le résultat exact.", 'fact' => 'Particulièrement efficace pour les problèmes mathématiques et logiques où le raisonnement en langage naturel manque de précision.'],
            ['name' => 'Chain-of-density', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🗜️', 'cat' => 'outils', 'definition' => "Technique de synthèse où l'IA génère des résumés de plus en plus denses d'un texte, capturant davantage d'information à chaque itération.", 'analogy' => "C'est comme passer d'un résumé de film de 2 pages à un synopsis d'1 paragraphe, puis à une phrase accrocheuse.", 'example' => "L'IA résume un rapport de 50 pages en 5 itérations\u{00A0}: 1 page, puis 1 paragraphe, puis 3 phrases, puis 1 phrase, puis 5 mots.", 'fact' => 'Développée par des chercheurs de Columbia et Salesforce, cette technique produit des résumés plus informatifs que les méthodes traditionnelles.'],
            ['name' => 'Directional stimulus prompting', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🧭', 'cat' => 'outils', 'definition' => "Utilise des indices ou stimuli directionnels subtils pour orienter l'IA vers un type de réponse ou un style de raisonnement spécifique.", 'analogy' => "C'est comme donner un coup de pouce à quelqu'un dans la bonne direction sans lui dire exactement où aller.", 'example' => "Fournir un mot-clé ou un début de phrase à l'IA pour l'orienter vers une réponse créative plutôt qu'analytique.", 'fact' => "Permet un contrôle fin de la sortie de l'IA sans avoir à écrire des instructions détaillées."],
            ['name' => 'Generated knowledge prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '💡', 'cat' => 'outils', 'definition' => "Demande à l'IA de générer des connaissances pertinentes sur un sujet avant de répondre à la question principale.", 'analogy' => "C'est comme réviser ses notes de cours avant un examen – tu te rafraîchis la mémoire avant de répondre.", 'example' => "Avant de répondre à « Quels sont les impacts de l'IA sur l'éducation\u{00A0}? », l'IA génère d'abord un résumé des avancées récentes en IA éducative.", 'fact' => "Améliore significativement la profondeur et l'exactitude des réponses, surtout pour des sujets spécialisés."],
            ['name' => 'Analogical prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🔀', 'cat' => 'outils', 'definition' => "Technique utilisant des analogies pour aider l'IA à transférer un raisonnement connu vers un problème nouveau ou complexe.", 'analogy' => "C'est comme expliquer le fonctionnement d'internet en le comparant au système postal – on transpose ce qu'on connaît.", 'example' => "Demander à l'IA d'expliquer la blockchain « comme si c'était un registre dans une caisse populaire que tout le monde peut consulter ».", 'fact' => 'Technique particulièrement efficace en pédagogie, elle rend les concepts abstraits accessibles à tous les niveaux.'],
            ['name' => 'Contrastive chain-of-thought', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '⚖️', 'cat' => 'outils', 'definition' => "Compare un raisonnement correct et un raisonnement incorrect dans la chaîne de pensée pour aider l'IA à mieux distinguer les bonnes des mauvaises approches.", 'analogy' => "C'est comme un prof qui montre un bon et un mauvais exemple de dissertation pour que les étudiants comprennent la différence.", 'example' => "Montrer à l'IA un calcul correct ET un calcul incorrect pour qu'elle comprenne où se situe l'erreur courante.", 'fact' => 'Permet une analyse plus nuancée et réduit les erreurs en rendant les pièges logiques explicites.'],
        ];

        foreach ($terms as $data) {
            $slug = Str::slug($data['name']);
            $term = Term::where('slug->fr_CA', $slug)->first();

            if (! $term) {
                $term = new Term;
                $term->is_published = true;
            }

            $term->type = $data['type'];
            $term->difficulty = $data['difficulty'];
            $term->icon = $data['icon'];
            $term->dictionary_category_id = $catIds[$data['cat']] ?? null;

            $term->setTranslation('name', 'fr_CA', $data['name']);
            $term->setTranslation('slug', 'fr_CA', $slug);
            $term->setTranslation('definition', 'fr_CA', $data['definition']);
            $term->setTranslation('analogy', 'fr_CA', $data['analogy']);
            $term->setTranslation('example', 'fr_CA', $data['example']);
            $term->setTranslation('did_you_know', 'fr_CA', $data['fact']);
            $term->save();
        }
    }
}
