<?php

declare(strict_types=1);

namespace Modules\Dictionary\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Modules\Dictionary\Models\Category;
use Modules\Dictionary\Models\Term;

class DictionaryPromptingSeeder extends Seeder
{
    public function run(): void
    {
        $catIds = [];
        foreach (['Outils et techniques' => 'outils'] as $name => $key) {
            $cat = Category::whereRaw("JSON_EXTRACT(name, '$.fr_CA') = ?", ['"' . $name . '"'])->first();
            if ($cat) {
                $catIds[$key] = $cat->id;
            }
        }

        $terms = [
            ['name' => 'ReAct (Reason + Act)', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '⚛️', 'cat' => 'outils', 'definition' => "Technique combinant raisonnement et action permettant a l'IA de planifier ses etapes puis d'interagir avec des outils externes pour executer des taches complexes.", 'analogy' => "C'est comme un plombier qui reflechit au probleme (raison) avant de prendre sa cle anglaise (action), puis ajuste son plan au fur et a mesure.", 'example' => "Pour repondre a 'Quel est le meilleur restaurant pres de mon hotel a Paris ?', l'IA raisonne, cherche la meteo, puis utilise cette info pour trouver un restaurant avec terrasse.", 'fact' => "ReAct est devenu le standard pour les agents IA autonomes en 2025-2026, utilise par ChatGPT, Claude et Gemini pour interagir avec des outils."],
            ['name' => 'Self-consistency', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🎯', 'cat' => 'outils', 'definition' => "Technique qui genere plusieurs raisonnements differents pour une meme question, puis selectionne la reponse la plus frequente par vote majoritaire.", 'analogy' => "C'est comme demander a 5 amis de resoudre un probleme de math separement, puis prendre la reponse sur laquelle la majorite s'entend.", 'example' => "Pour un probleme de logique, l'IA genere 10 chaines de pensee differentes et choisit la reponse qui revient 7 fois sur 10.", 'fact' => "Cette technique reduit les hallucinations de 15 a 25 % sur les taches de raisonnement mathematique et logique."],
            ['name' => 'Tree-of-thought', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🌳', 'cat' => 'outils', 'definition' => "Explore plusieurs chemins de raisonnement possibles sous forme d'arborescence, permettant des retours en arriere et des evaluations de chaque branche.", 'analogy' => "C'est comme un joueur d'echecs qui visualise plusieurs coups possibles et leurs consequences avant de deplacer sa piece.", 'example' => "Pour resoudre un casse-tete creatif comme ecrire un poeme avec des contraintes, l'IA explore differentes directions et garde les meilleures.", 'fact' => "Tree-of-thought depasse les approches lineaires en autorisant l'exploration parallele, comme le fait le cerveau humain."],
            ['name' => 'Emotion prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '💖', 'cat' => 'outils', 'definition' => "Technique ajoutant une charge emotionnelle ou cognitive au prompt pour ameliorer la precision et l'engagement des reponses de l'IA.", 'analogy' => "C'est comme dire a un etudiant 'cet examen est tres important pour ta carriere' — la pression emotionnelle le pousse a mieux performer.", 'example' => "Ajouter 'C'est tres important pour mon travail, sois le plus precis possible' a la fin d'un prompt augmente la qualite de la reponse.", 'fact' => "Validee par Microsoft et Google en 2024, cette technique ameliore la precision des reponses de 15 a 40 % selon les taches."],
            ['name' => 'APE (Automatic Prompt Engineer)', 'type' => 'acronym', 'difficulty' => 'advanced', 'icon' => '🤖', 'cat' => 'outils', 'definition' => "Systeme ou l'IA genere et optimise automatiquement ses propres prompts pour accomplir une tache donnee, sans intervention humaine.", 'analogy' => "C'est comme un cuisinier qui ajuste sa recette tout seul a force d'essais jusqu'a trouver le gout parfait.", 'example' => "APE peut creer automatiquement le prompt optimal pour qu'une IA genere des descriptions de produits efficaces pour un site de commerce.", 'fact' => "APE a demontre sa capacite a generer des prompts plus performants que ceux crees manuellement par des experts humains."],
            ['name' => 'Self-refine', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🔄', 'cat' => 'outils', 'definition' => "L'IA genere une premiere reponse, l'evalue elle-meme, identifie les faiblesses et l'ameliore iterativement sans intervention humaine.", 'analogy' => "C'est comme relire ta dissertation trois fois en corrigeant les fautes et en ameliorant les phrases a chaque passage.", 'example' => "L'IA ecrit un courriel professionnel, le relit, trouve le ton trop familier, et le reformule de maniere plus formelle.", 'fact' => "Self-refine permet d'atteindre une qualite proche de la revision humaine en seulement 2 a 3 iterations automatiques."],
            ['name' => 'Reflexion', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🪞', 'cat' => 'outils', 'definition' => "Technique ou l'IA simule une reflexion meta-cognitive sur ses erreurs passees pour corriger son raisonnement dans les tentatives suivantes.", 'analogy' => "C'est comme un joueur de hockey qui revisionne ses parties pour identifier ses erreurs et s'ameliorer au prochain match.", 'example' => "Apres avoir echoue a resoudre un probleme de code, l'IA analyse ce qui n'a pas fonctionne et ajuste sa strategie.", 'fact' => "La reflexion peut ameliorer les performances de l'IA de 50 a 75 % sur des taches de raisonnement complexe."],
            ['name' => 'Chain-of-verification', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '✅', 'cat' => 'outils', 'definition' => "Methode ou l'IA genere une reponse, puis cree des questions de verification pour confirmer l'exactitude de chaque affirmation.", 'analogy' => "C'est comme un journaliste qui verifie ses sources avant de publier un article — chaque fait est valide independamment.", 'example' => "Apres avoir genere une biographie, l'IA pose des questions comme 'Est-ce que cette date de naissance est correcte ?' et corrige si necessaire.", 'fact' => "Technique cruciale pour reduire les hallucinations, surtout pour les contenus factuels et les donnees sensibles."],
            ['name' => 'Step-back prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🔭', 'cat' => 'outils', 'definition' => "Demande a l'IA de prendre du recul et de considerer les principes generaux avant de repondre a une question specifique.", 'analogy' => "C'est comme regarder la carte du Quebec en entier avant de zoomer sur ton quartier pour trouver un chemin.", 'example' => "Au lieu de repondre directement a 'Pourquoi le ciel est bleu ?', l'IA reflechit d'abord aux principes de la diffusion de la lumiere.", 'fact' => "Cette technique ameliore significativement la qualite des reponses sur les questions scientifiques et techniques complexes."],
            ['name' => 'Least-to-most prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🪜', 'cat' => 'outils', 'definition' => "Decompose un probleme complexe en sous-problemes du plus simple au plus difficile, les resolvant sequentiellement de facon cumulative.", 'analogy' => "C'est comme monter un escalier marche par marche au lieu d'essayer de sauter directement en haut.", 'example' => "Pour traduire un texte technique, l'IA traduit d'abord les mots cles, puis les phrases simples, puis les paragraphes complexes.", 'fact' => "Cette approche pedagogique aide l'IA a mieux gerer la complexite et reduit les erreurs sur les problemes a plusieurs etapes."],
            ['name' => 'Role prompting', 'type' => 'ai_term', 'difficulty' => 'beginner', 'icon' => '🎭', 'cat' => 'outils', 'definition' => "Technique attribuant un role specifique a l'IA (expert, professeur, avocat) pour adapter sa voix, son ton et son expertise a un contexte precis.", 'analogy' => "C'est comme demander a un acteur de jouer un personnage — il adapte tout son comportement au role.", 'example' => "Dire a ChatGPT 'Tu es un nutritionniste experimente' avant de poser des questions sur l'alimentation.", 'fact' => "C'est la technique de prompting la plus utilisee au quotidien, souvent sans que les utilisateurs s'en rendent compte."],
            ['name' => 'Meta-prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🧩', 'cat' => 'outils', 'definition' => "Technique qui utilise des prompts pour generer ou ameliorer d'autres prompts, optimisant ainsi la communication avec l'IA.", 'analogy' => "C'est comme ecrire un mode d'emploi pour rediger de meilleurs modes d'emploi — tu ameliores le processus lui-meme.", 'example' => "Demander a l'IA 'Cree le meilleur prompt possible pour generer des logos minimalistes avec DALL-E'.", 'fact' => "Le meta-prompting est a la base des outils comme APE et des 'prompt generators' qui automatisent la creation de prompts."],
            ['name' => 'Graph-of-thought', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🕸️', 'cat' => 'outils', 'definition' => "Modelise le raisonnement de l'IA comme un graphe non lineaire ou les idees sont interconnectees, depassant les limites de l'arbre de pensee.", 'analogy' => "C'est comme une carte mentale ou chaque idee est reliee a plusieurs autres, formant un reseau de connections.", 'example' => "Pour planifier un voyage complexe, l'IA connecte les contraintes de budget, meteo, activites et transport dans un reseau de decisions.", 'fact' => "Extension du Tree-of-thought, le Graph-of-thought permet de modeliser des problemes ou les elements sont interdependants."],
            ['name' => 'Skeleton-of-thought', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🦴', 'cat' => 'outils', 'definition' => "L'IA genere d'abord un squelette structurel de la reponse (plan, titres), puis remplit chaque section en parallele pour accelerer la generation.", 'analogy' => "C'est comme dessiner les contours d'une maison avant de construire les murs et poser le toit.", 'example' => "Pour rediger un article de blogue, l'IA cree d'abord les 5 titres de sections, puis ecrit le contenu de chacune simultanement.", 'fact' => "Cette technique peut accelerer la generation de contenu de 2 a 3 fois tout en ameliorant la coherence globale."],
            ['name' => 'Program-of-thought', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '💻', 'cat' => 'outils', 'definition' => "L'IA exprime son raisonnement sous forme de code executable (Python, JavaScript) qui peut etre verifie automatiquement.", 'analogy' => "C'est comme ecrire un programme pour calculer tes impots au lieu de le faire a la main — le code ne se trompe pas.", 'example' => "Pour des calculs financiers complexes, l'IA genere un script Python qui effectue les operations et retourne le resultat exact.", 'fact' => "Particulierement efficace pour les problemes mathematiques et logiques ou le raisonnement en langage naturel manque de precision."],
            ['name' => 'Chain-of-density', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🗜️', 'cat' => 'outils', 'definition' => "Technique de synthese ou l'IA genere des resumes de plus en plus denses d'un texte, capturant davantage d'information a chaque iteration.", 'analogy' => "C'est comme passer d'un resume de film de 2 pages a un synopsis d'1 paragraphe, puis a une phrase accrocheuse.", 'example' => "L'IA resume un rapport de 50 pages en 5 iterations : 1 page, puis 1 paragraphe, puis 3 phrases, puis 1 phrase, puis 5 mots.", 'fact' => "Developpee par des chercheurs de Columbia et Salesforce, cette technique produit des resumes plus informatifs que les methodes traditionnelles."],
            ['name' => 'Directional stimulus prompting', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🧭', 'cat' => 'outils', 'definition' => "Utilise des indices ou stimuli directionnels subtils pour orienter l'IA vers un type de reponse ou un style de raisonnement specifique.", 'analogy' => "C'est comme donner un coup de pouce a quelqu'un dans la bonne direction sans lui dire exactement ou aller.", 'example' => "Fournir un mot-cle ou un debut de phrase a l'IA pour l'orienter vers une reponse creative plutot qu'analytique.", 'fact' => "Permet un controle fin de la sortie de l'IA sans avoir a ecrire des instructions detaillees."],
            ['name' => 'Generated knowledge prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '💡', 'cat' => 'outils', 'definition' => "Demande a l'IA de generer des connaissances pertinentes sur un sujet avant de repondre a la question principale.", 'analogy' => "C'est comme reviser ses notes de cours avant un examen — tu te rafraichis la memoire avant de repondre.", 'example' => "Avant de repondre a 'Quels sont les impacts de l'IA sur l'education ?', l'IA genere d'abord un resume des avancees recentes en IA educative.", 'fact' => "Ameliore significativement la profondeur et l'exactitude des reponses, surtout pour des sujets specialises."],
            ['name' => 'Analogical prompting', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🔀', 'cat' => 'outils', 'definition' => "Technique utilisant des analogies pour aider l'IA a transferer un raisonnement connu vers un probleme nouveau ou complexe.", 'analogy' => "C'est comme expliquer le fonctionnement d'internet en le comparant au systeme postal — on transpose ce qu'on connait.", 'example' => "Demander a l'IA d'expliquer la blockchain 'comme si c'etait un registre dans une caisse populaire que tout le monde peut consulter'.", 'fact' => "Technique particulierement efficace en pedagogie, elle rend les concepts abstraits accessibles a tous les niveaux."],
            ['name' => 'Contrastive chain-of-thought', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '⚖️', 'cat' => 'outils', 'definition' => "Compare un raisonnement correct et un raisonnement incorrect dans la chaine de pensee pour aider l'IA a mieux distinguer les bonnes des mauvaises approches.", 'analogy' => "C'est comme un prof qui montre un bon et un mauvais exemple de dissertation pour que les etudiants comprennent la difference.", 'example' => "Montrer a l'IA un calcul correct ET un calcul incorrect pour qu'elle comprenne ou se situe l'erreur courante.", 'fact' => "Permet une analyse plus nuancee et reduit les erreurs en rendant les pieges logiques explicites."],
        ];

        foreach ($terms as $data) {
            $slug = Str::slug($data['name']);
            $term = Term::where('slug->fr_CA', $slug)->first();

            if (! $term) {
                $term = new Term();
                $term->is_published = true;
            }

            $term->type = $data['type'];
            $term->difficulty = $data['difficulty'];
            $term->icon = $data['icon'];
            $term->dictionary_category_id = $catIds[$data['cat']] ?? null;

            $term->setTranslation('name', 'fr_CA', $data['name']);
            $term->setTranslation('slug', 'fr_CA', $slug);
            $term->setTranslation('definition', 'fr_CA', $data['definition']);
            $term->setTranslation('analogy', 'fr_CA', $data['analogy']);
            $term->setTranslation('example', 'fr_CA', $data['example']);
            $term->setTranslation('did_you_know', 'fr_CA', $data['fact']);
            $term->save();
        }
    }
}
