<?php

declare(strict_types=1);

namespace Modules\Dictionary\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Modules\Dictionary\Models\Category;
use Modules\Dictionary\Models\Term;

class DictionaryNewTermsSeeder extends Seeder
{
    public function run(): void
    {
        $catIds = [];
        foreach (['Concepts fondamentaux' => 'concepts', 'Sécurité et éthique' => 'securite', 'Outils et techniques' => 'outils', 'Données et traitement' => 'donnees'] as $name => $key) {
            $cat = Category::whereRaw("JSON_EXTRACT(name, '$.fr_CA') = ?", ['"' . $name . '"'])->first();
            if ($cat) {
                $catIds[$key] = $cat->id;
            }
        }

        $terms = [
            ['name' => 'Biais algorithmique', 'type' => 'ai_term', 'difficulty' => 'beginner', 'icon' => '🎯', 'cat' => 'securite', 'definition' => "Une erreur systématique dans un système d'IA qui crée des résultats injustes ou discriminatoires envers certains groupes.", 'analogy' => "C'est comme un arbitre au hockey qui siffle toujours les pénalités contre la même équipe parce qu'il a un préjugé.", 'example' => 'Un logiciel de recrutement qui rejette automatiquement les CV des femmes pour des postes techniques.', 'fact' => "Les biais viennent souvent des données historiques utilisées pour entraîner l'IA, qui reflètent nos propres préjugés humains."],
            ['name' => 'IA multimodale', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🎭', 'cat' => 'concepts', 'definition' => "Une intelligence artificielle capable de comprendre et de générer plusieurs types de médias à la fois : texte, images et son.", 'analogy' => "C'est comme une personne qui peut lire un livre, écouter la radio et regarder un film en même temps pour comprendre une histoire.", 'example' => "ChatGPT qui peut analyser une photo de ton frigo et te suggérer une recette avec les ingrédients qu'il voit.", 'fact' => "L'IA multimodale se rapproche de la façon dont les humains perçoivent le monde avec leurs cinq sens."],
            ['name' => 'Chatbot', 'type' => 'ai_term', 'difficulty' => 'beginner', 'icon' => '💬', 'cat' => 'concepts', 'definition' => 'Un programme informatique conçu pour simuler une conversation avec des utilisateurs humains, par texte ou par voix.', 'analogy' => "C'est comme un commis au service à la clientèle qui ne dort jamais et répond instantanément, mais c'est un robot.", 'example' => "La petite bulle de clavardage sur le site de ta banque qui répond à tes questions sur tes comptes.", 'fact' => "Le tout premier chatbot, ELIZA, a été créé dans les années 60 et jouait le rôle d'un psychothérapeute."],
            ['name' => 'Apprentissage automatique', 'type' => 'ai_term', 'difficulty' => 'beginner', 'icon' => '📈', 'cat' => 'concepts', 'definition' => "Un sous-domaine de l'IA où les ordinateurs apprennent à effectuer des tâches sans être explicitement programmés pour chaque étape.", 'analogy' => "C'est comme apprendre à un enfant à faire du vélo : on ne lui donne pas un manuel, il essaie, tombe, et s'améliore.", 'example' => "Netflix qui apprend tes goûts au fur et à mesure que tu regardes des séries pour te faire de meilleures suggestions.", 'fact' => "On utilise souvent le terme anglais « Machine Learning » pour désigner ce concept."],
            ['name' => 'Réseau de neurones', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🧠', 'cat' => 'concepts', 'definition' => "Un système informatique inspiré du fonctionnement du cerveau humain, composé de couches de nœuds interconnectés.", 'analogy' => "C'est comme une immense équipe de relais où chaque personne passe l'information à la suivante en la modifiant un peu.", 'example' => "La technologie utilisée par ton téléphone pour reconnaître ton visage et déverrouiller l'écran.", 'fact' => "Les réseaux de neurones profonds (Deep Learning) peuvent avoir des centaines de couches, d'où le nom « profond »."],
            ['name' => 'Open source', 'type' => 'explainer', 'difficulty' => 'beginner', 'icon' => '🔓', 'cat' => 'outils', 'definition' => "Un logiciel dont le code source est accessible au public, permettant à quiconque de l'utiliser, le modifier et le distribuer.", 'analogy' => "C'est comme une recette de grand-mère publiée dans le journal : tout le monde peut la cuisiner et l'améliorer.", 'example' => "Le système d'exploitation Linux ou le gestionnaire de contenu WordPress sont des projets open source.", 'fact' => "Beaucoup d'outils d'IA modernes sont open source, ce qui accélère grandement l'innovation mondiale."],
            ['name' => 'Cloud computing', 'type' => 'explainer', 'difficulty' => 'beginner', 'icon' => '☁️', 'cat' => 'outils', 'definition' => "La distribution de services informatiques (serveurs, stockage, bases de données) via internet plutôt que localement.", 'analogy' => "C'est comme louer un espace dans un entrepôt géant et sécurisé au lieu d'empiler toutes tes boîtes dans ton garage.", 'example' => "Google Drive ou iCloud, qui gardent tes photos en sécurité sur des serveurs à distance.", 'fact' => "Le « nuage » n'est pas dans le ciel\u{00A0}: ce sont des milliers de centres de données physiques remplis d'ordinateurs."],
            ['name' => 'Modèle de langage', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '📝', 'cat' => 'concepts', 'definition' => "Un type d'IA entraîné sur d'immenses quantités de texte pour comprendre, prédire et générer du langage humain.", 'analogy' => "C'est comme un perroquet super intelligent qui a lu tous les livres de la bibliothèque et qui sait prédire le prochain mot.", 'example' => "Le modèle GPT-4 est le moteur qui fait fonctionner ChatGPT.", 'fact' => "Ces modèles ne « comprennent » pas le sens comme nous, ils calculent des probabilités mathématiques entre les mots."],
            ['name' => "Données d'entraînement", 'type' => 'ai_term', 'difficulty' => 'beginner', 'icon' => '📦', 'cat' => 'donnees', 'definition' => "L'ensemble des informations (textes, images, sons) utilisées pour apprendre à une IA comment accomplir sa tâche.", 'analogy' => "C'est comme les manuels scolaires et les exercices qu'un étudiant utilise pour étudier avant son examen final.", 'example' => "Des milliers de photos de chats et de chiens montrées à une IA pour qu'elle apprenne à les différencier.", 'fact' => "La qualité de l'IA dépend directement de la qualité des données\u{00A0}: Garbage in, garbage out."],
            ['name' => 'Boucle de rétroaction', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🔄', 'cat' => 'donnees', 'definition' => "Un processus où les résultats de l'IA sont réinjectés dans le système pour l'améliorer continuellement.", 'analogy' => "C'est comme un coach qui te regarde jouer et te donne des conseils après chaque partie pour que tu sois meilleur.", 'example' => "Quand tu dis à Spotify que tu n'aimes pas une chanson, il ajuste son algorithme pour ne plus te jouer ce genre.", 'fact' => "Les boucles de rétroaction peuvent parfois créer des chambres d'écho si elles ne sont pas bien surveillées."],
            ['name' => 'IA explicable', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '🔍', 'cat' => 'securite', 'definition' => "Des systèmes d'IA conçus pour que leurs actions et décisions puissent être comprises par des humains.", 'analogy' => "C'est comme un prof de math qui te demande de montrer ta démarche sur ta feuille d'examen, pas juste la réponse.", 'example' => "Une banque qui utilise une IA pour les prêts et qui peut t'expliquer exactement pourquoi ta demande a été refusée.", 'fact' => "C'est un enjeu majeur, car beaucoup d'IA modernes sont des « boîtes noires » dont on ne comprend pas le fonctionnement."],
            ['name' => 'IA responsable', 'type' => 'ai_term', 'difficulty' => 'beginner', 'icon' => '⚖️', 'cat' => 'securite', 'definition' => "Une approche de développement de l'IA qui assure que la technologie est éthique, transparente et respecte les lois.", 'analogy' => "C'est comme construire un pont en s'assurant qu'il est sécuritaire pour tout le monde et ne pollue pas la rivière.", 'example' => "Mettre en place des garde-fous pour empêcher une IA de générer des discours haineux ou des fausses nouvelles.", 'fact' => "Le Canada est souvent cité comme un leader mondial dans la réflexion sur l'éthique de l'IA."],
            ['name' => 'Test de Turing', 'type' => 'ai_term', 'difficulty' => 'beginner', 'icon' => '🤔', 'cat' => 'concepts', 'definition' => "Une expérience pour déterminer si une machine est capable de faire preuve d'intelligence indiscernable de celle d'un humain.", 'analogy' => "C'est comme un test de goût à l'aveugle : si tu ne peux pas dire si c'est du beurre ou de la margarine, la margarine a réussi.", 'example' => "Si tu chattes avec un ordinateur et que tu es convaincu de parler à une vraie personne, la machine a passé le test.", 'fact' => "Aujourd'hui, beaucoup d'IA réussissent ce test, ce qui nous force à repenser notre définition de l'intelligence."],
            ['name' => 'Automatisation', 'type' => 'explainer', 'difficulty' => 'beginner', 'icon' => '⚙️', 'cat' => 'outils', 'definition' => "L'utilisation de la technologie pour effectuer des tâches avec une intervention humaine minimale.", 'analogy' => "C'est comme un lave-vaisselle : tu le remplis, tu pèses sur un bouton, et il fait la job pendant que tu fais autre chose.", 'example' => "L'envoi automatique d'un courriel de confirmation après que tu aies acheté quelque chose en ligne.", 'fact' => "L'automatisation vise souvent les tâches répétitives et ennuyantes pour libérer les humains pour du travail créatif."],
            ['name' => 'Synthèse vocale', 'type' => 'ai_term', 'difficulty' => 'beginner', 'icon' => '🗣️', 'cat' => 'outils', 'definition' => "Une technologie qui convertit le texte écrit en parole artificielle (Text-to-Speech).", 'analogy' => "C'est comme avoir un lecteur de nouvelles virtuel qui lit ton journal à voix haute pour toi.", 'example' => "La voix du GPS dans ton auto qui te dit « Tournez à gauche » ou celle de Siri et Alexa.", 'fact' => "Les voix synthétiques modernes peuvent maintenant imiter les émotions et les intonations humaines de façon très réaliste."],
            ['name' => 'Vision par ordinateur', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '👁️', 'cat' => 'concepts', 'definition' => "Un domaine de l'IA qui permet aux ordinateurs de « voir », d'analyser et de comprendre des images ou des vidéos.", 'analogy' => "C'est comme donner des yeux et un cerveau visuel à un ordinateur pour qu'il reconnaisse ce qu'il regarde.", 'example' => "Une voiture autonome qui détecte les panneaux d'arrêt, les piétons et les autres véhicules sur la route.", 'fact' => "Cette technologie est aussi utilisée en médecine pour aider à détecter des tumeurs sur des radiographies."],
            ['name' => 'Prompt engineering', 'type' => 'ai_term', 'difficulty' => 'intermediate', 'icon' => '✏️', 'cat' => 'outils', 'definition' => "L'art de formuler des instructions précises (prompts) pour obtenir les meilleurs résultats possibles d'une IA générative.", 'analogy' => "C'est comme savoir exactement comment formuler ton vœu au génie pour ne pas avoir de mauvaises surprises.", 'example' => "Au lieu de dire « écris un texte », dire « écris un courriel professionnel de 100 mots pour remercier un client ».", 'fact' => "C'est devenu un nouveau métier très recherché avec l'essor des outils comme ChatGPT et Midjourney."],
            ['name' => 'AGI', 'type' => 'acronym', 'difficulty' => 'advanced', 'icon' => '🌟', 'cat' => 'concepts', 'definition' => "Intelligence artificielle générale – une IA hypothétique qui posséderait une intelligence égale ou supérieure à l'humain dans tous les domaines.", 'analogy' => "C'est comme avoir un employé capable de faire la job du comptable, du créatif et du PDG en même temps, et mieux qu'eux.", 'example' => "C'est le type d'IA qu'on voit dans les films de science-fiction, comme C-3PO ou HAL 9000.", 'fact' => "Nous n'avons pas encore atteint l'AGI\u{00A0}; les IA actuelles sont « étroites » (bonnes dans une seule tâche précise)."],
            ['name' => 'Alignement IA', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '🎯', 'cat' => 'securite', 'definition' => "Le défi de s'assurer que les objectifs et comportements d'une IA correspondent bien aux valeurs et intentions humaines.", 'analogy' => "C'est comme dresser un chien très puissant pour qu'il protège la maison sans jamais mordre le facteur ou les invités.", 'example' => "Programmer une IA pour 'guérir le cancer' sans qu'elle décide que la meilleure solution est d'éliminer tous les humains.", 'fact' => "C'est considéré par plusieurs experts comme le problème le plus important à résoudre avant l'arrivée de l'AGI."],
            ['name' => 'Embeddings', 'type' => 'ai_term', 'difficulty' => 'advanced', 'icon' => '📐', 'cat' => 'donnees', 'definition' => "Une représentation numérique de mots ou phrases sous forme de vecteurs (listes de nombres) pour que l'ordinateur comprenne leur sens.", 'analogy' => "C'est comme donner des coordonnées GPS à chaque mot pour voir lesquels sont proches (ex\u{00A0}: « roi » est proche de « reine »).", 'example' => "C'est ce qui permet à Google de comprendre que si tu cherches « auto », les résultats contenant « voiture » sont aussi pertinents.", 'fact' => "Les embeddings permettent de faire des calculs mathématiques avec le sens des mots (Roi - Homme + Femme = Reine)."],
        ];

        foreach ($terms as $data) {
            $slug = Str::slug($data['name']);
            $term = Term::where('slug->fr_CA', $slug)->first();

            if (! $term) {
                $term = new Term();
                $term->is_published = true;
            }

            $term->type = $data['type'];
            $term->difficulty = $data['difficulty'];
            $term->icon = $data['icon'];
            $term->dictionary_category_id = $catIds[$data['cat']] ?? null;

            $term->setTranslation('name', 'fr_CA', $data['name']);
            $term->setTranslation('slug', 'fr_CA', $slug);
            $term->setTranslation('definition', 'fr_CA', $data['definition']);
            $term->setTranslation('analogy', 'fr_CA', $data['analogy']);
            $term->setTranslation('example', 'fr_CA', $data['example']);
            $term->setTranslation('did_you_know', 'fr_CA', $data['fact']);
            $term->save();
        }
    }
}
