[program:horizon]
process_name=%(program_name)s
command=php /var/www/html/artisan horizon
directory=/var/www/html
user=www-data
autostart=true
autorestart=true
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=/var/log/supervisor/horizon.log
stderr_logfile=/var/log/supervisor/horizon.err
