<?php

declare(strict_types=1);

/**
 * @author  MEMORA solutions <info@memora.ca> (https://memora.solutions)
 *
 * @project laveille.ai
 *
 * Versioning SemVer 2.0.0 — https://semver.org
 *
 * Règles de bump (Conventional Commits) :
 *   feat:        -> MINOR (nouvelle fonctionnalité, rétro-compatible)
 *   fix:         -> PATCH (correction de bug, rétro-compatible)
 *   feat!: ou
 *   BREAKING:    -> MAJOR (casse rétro-compatibilité)
 *   chore/test/refactor/docs/style/ci -> pas de bump
 *
 * Historique :
 *   1.18.1 · 2026-05-18 · #235 P17 fix 404 prod actionnables : (a) redirects 301 sitemaps legacy bots `/sitemap_index.xml` + `/sitemaps.xml` + `/sitemap.xml.gz` + `/atom.xml` → `/sitemap.xml` via Route::redirect inline dans Modules/SEO/routes/web.php (DRY natif Laravel) ; (b) wildcard `/outil/{slug?}` (typo singular legacy WP) → smart redirect 301 vers `/outils/{slug}` si Tool::where('slug')->exists() sinon `/outils` (closure inline dans Modules/Tools/routes/web.php, regex `[a-z0-9\-]*` accepte vide aussi) ; (c) `/actualites/{slug}` refondu en closure smart : NewsArticle::where('slug')->first() → si trouvé délègue PublicNewsController::show(article), sinon 301 vers `/actualites` (Modules/News/routes/web.php — remplace ancien route model binding qui throwait 404 sur slugs orphelins) ; (d) `/auteur/{slug}/page/{n}` legacy WordPress pagination → 301 vers `/auteur/{slug}` (auteur unique <10 articles, pagination inutile) dans Modules/FrontTheme/routes/web.php ; (e) JS stubs `/js/ga4-events.js` + `/js/sw-register.js` + `/sw.js` déjà 200 OK prod (false 404 dans rapport user). 9 tests Pest reflexifs verts (14 assertions, route inspection pattern pour éviter SQLite settings bloqueur). Codename fix-404-redirects.
 *   1.18.0 · 2026-05-18 · #234 EEAT byline + page auteur Stéphane Lapointe activée (matériel user fourni) — 5 photos optimisées (webp+jpg 80/256 + schema 1200), bio mise à jour avec livre « L'IA sans se faire poursuivre » Édition 2026 + 20+ ans gouvernance numérique + L'Ancienne-Lorette QC, LinkedIn `https://www.linkedin.com/in/lapointestephane` (rel="me" IndieWeb critique), 4 qualifications (Fondateur MEMORA / Auteur livre 2026 / Expert 20+ ans / Spécialiste Loi 25+RGPD+AI Act), 7 entrées knowsAbout Schema.org Person, H1 "Nom — Rôle" pour signal expertise immédiat, picture webp+jpg fallback responsive, byline cards et author-box bottom blog/show utilisent photo réelle (vs logo-avatar générique), AuthorController enrichi (@id, knowsAbout, image dédiée file_exists fallback, limit 10 articles), réutilise composant DRY `<x-fronttheme::book-promo>` sur page auteur, 14 nouveaux tests Pest reflexifs AuthorPageTest + 3 enrichis AuthorsTranslationTest (27 verts / 61 assertions total). Sitemap.xml + link rel="author" master layout + meta name="author" déjà cablés depuis S84 scaffolding. Codename eeat-stephane-active.
 *   1.17.2 · 2026-05-18 · #232 désactive temporairement /annuaire/classement (1 seul contributor solo, classement vide d'intérêt). Feature flag réversible `directory.leaderboard.enabled` (default false, env DIRECTORY_LEADERBOARD_ENABLED) dans Modules/Directory/config/config.php (pattern réutilisé de `category_alerts`). Route /annuaire/classement conservée mais wrappée dans closure qui redirige 302 vers /annuaire avec flash session `info` ("Le classement sera disponible quand plusieurs contributeurs participeront à l'annuaire.") quand flag off ; déléguée à `app(LeaderboardController::class)->index()` quand flag on. Nom de route `directory.leaderboard` préservé pour que `Route::has()` reste vrai et que les gates @if combinent Route::has + config flag (double sécurité, traçabilité). 5 gates @if mis à jour dans header.blade.php (4 = mega-menu desktop + 2 sub-menu mobile + offcanvas mobile) + 1 gate dans footer.blade.php. Pour réactiver dès que ≥3 contributeurs réguliers : DIRECTORY_LEADERBOARD_ENABLED=true (.env prod) — pas besoin de redéployer. 6 tests Pest verts (15 assertions) — reflexifs source-based pour éviter dépendance DB lourde (closure inline + nom route + gates + config default). Sitemap.xml vérifié zéro référence préalable (jamais référencé). Codename leaderboard-feature-flag.
 *   1.17.1 · 2026-05-18 · #231 NBSP typographie FR site-wide — helper `lv_typo_fr()` autoload via composer.json `files[]` + `app/Providers/AppServiceProvider::register()` (idempotent, double layer prod-safe). Directive Blade `@typo($text)` + macro `Str::typoFr()` enregistrées dans `boot()`. Règles appliquées : (1) NBSP avant `? ! : ; »` (ponctuation double FR) ; (2) NBSP après `«` (guillemet ouvrant) ; (3) NBSP entre chiffre et unité (`%`, `$`, `€`, `°C`, `M$`, `M€`, `k€`, `k$`). Préservation 3 couches : (a) URL — pas de NBSP injecté dans `href="...?q=1"` ; (b) HTML — segmentation balises `<...>` / texte, balises laissées intactes ; (c) JSON — détection auto `{...}` ou `[...]`, walk récursif sur valeurs string uniquement, ré-encode JSON valide (préserve colonnes spatie/laravel-translatable `{"fr_CA":"..."}`). 19 tests Pest verts (40 assertions). Patch composant `<x-fronttheme::book-promo>` user-visible (title/subtitle/descriptions) → fix bug screenshot user `?` rejeté + `7\n%` séparés. Command Artisan `php artisan typo:apply-fr {--dry} {--table=*}` idempotente avec plan curated 8 tables (articles, ads_placements, directory_tools, dictionary_terms, news_articles, pages, faqs, testimonials). Codename typo-fr-nbsp.
 *   1.17.0 · 2026-05-18 · #230 remplace pub Nexus Neural par livre auteur « L'IA sans se faire poursuivre : guide pratique pour PME et professionnels — Édition 2026 ». Composant Blade réutilisable `<x-fronttheme::book-promo>` (DRY) avec 20 props (title/subtitle/author/cover_url_webp/cover_url_jpg/cta_url/schema/variant/etc.). Schema.org Book JSON-LD complet (Person Stéphane Lapointe + Organization MEMORA solutions + Offer Amazon CAD). WCAG 2.2 AA (min-height 44px CTA, focus-visible orange #C2410C, alt SEO descriptif Loi 25/RGPD/AI Act/PME). 4 images optimisées dans `public/images/books/` : webp 600 ~52KB, jpg 600 ~121KB (fallback compat réseaux sociaux), webp 300 ~21KB (mobile thumbnail), og 1200×630 ~54KB (Facebook/LinkedIn/Twitter cards). Responsive flex-row desktop / flex-column mobile <640px. Alpine.js x-collapse description longue toggle. CTA target=_blank + rel="noopener sponsored". Enhancement `AdsRenderer::render()` détecte `<x-` dans `ad_code` et compile via `Blade::render()` (pattern réutilisable pour toute pub à base de composant). DB ads : id=1 renommé `nexus-neural` → `book-author`, id=2 `article-inline` (auto-injection après 3e paragraphe articles) — les 2 utilisent `<x-fronttheme::book-promo variant="inline" />`. Migration `2026_05_18_120000_replace_nexus_neural_ads_with_book_promo.php` propage le changement DB en prod. 11 tests Pest verts (28 assertions). Codename book-promo-component.
 *   1.16.2 · 2026-05-18 · #229 fix popup newsletter /blog — bouton fermeture 14×26 → 44×44 px (WCAG 2.5.5 AAA) + cible touch mobile fiable + ESC handler explicite (delegation $(document)) + click backdrop ferme + data-bs-dismiss="modal" fallback Bootstrap natif + delegation click closeBtn (résiste au re-render DOM) + modal-dialog-scrollable + max-height calc(100vh - 40px) + overflow-y:auto !important sur modal-content (fix Bootstrap 5.0.1 cascade qui forçait overflow:hidden) + box-sizing:border-box inputs + font-size 16px (anti-zoom iOS) + media query mobile <480px margin/max-width adaptés. Cause racine confirmée Playwright prod 375×667 : modal débordait bottom 672>667, X 14×26 inatteignable touch, modal-content computed overflow:hidden empêchait scroll vers champs/consent/submit. Codename popup-newsletter-fix.
 *   1.16.1 · 2026-05-18 · #227 fix migration JSON_UNQUOTE compat SQLite — wrap `if (DB::getDriverName() === 'mysql')` autour des statements MySQL-only dans Modules/Dictionary/database/migrations/2026_05_05_180100_set_transformer_case_sensitive.php (up + down). Débloque Pest local (SQLite in-memory) qui plantait sur JSON_UNQUOTE/JSON_EXTRACT inexistants en SQLite. Aucun impact prod (MySQL exécute toujours la data migration originelle). Codename pest-sqlite-unblocked.
 *   1.16.0 · 2026-05-18 · #226 unsubscribe v2 — refonte complète flux désabonnement newsletter. Migration colonnes dédiées (unsubscribe_token, unsubscribed_at, unsubscribe_reason). Vue dédiée avec confirmation + raison optionnelle + routes web sécurisées par token signé. Tests Pest couvrant nominal/expired/invalid/double-click. Codename unsubscribe-v2.
 *   1.15.2 · 2026-05-17 · #226 fix assets admin post-login — retrait `splash-screen.css` orphelin (CSS jamais déployé, 404 console) dans Modules/Auth/resources/views/layouts/app.blade.php + Modules/Backoffice/resources/views/themes/backend/layouts/admin.blade.php + retrait blocs JS dynamiques associés (createElement splash). Standardisation `apexcharts.min.js` sur CDN jsdelivr v4.4.0 (cohérence stats/index.blade.php S89) dans dashboard/index.blade.php + revenue/index.blade.php (élimine asset local manquant). Codename admin-assets-fix. Console admin propre post-login user S95.
 *   1.15.1 · 2026-05-17 · #225 fix login bloqué — retrait `<script src="auth/plugins/preline/preline.js">` orphelin (404 console, fichier jamais déployé) dans Modules/Auth/resources/views/layouts/guest.blade.php + ajout `<meta name="mobile-web-app-capable" content="yes">` (deprecation warning Chrome, apple-mobile-web-app-capable conservé pour compat iOS Safari). Codename login-fix. Bloqueur user signalé S95 ; 415 Livewire résolu en parallèle via purge Cloudflare cache.
 *   1.15.0 · 2026-05-14 · #211 Boutique Phase 1 — audit t-shirt Gelato + correction désync majeure. Migration colonnes dédiées (gelato_store_product_id varchar 64 indexé, legacy_gelato_uid backup, gelato_synced_at). GelatoSyncService (fetch store API ecommerce.gelatoapis.com + transformToLocalVariants : 9 couleurs Gildan 5000 hex, size_prices avec SIZE_SURCHARGE 2XL+3/3XL+5/4XL+7/5XL+9, variant_ids + product_uids par taille). Command ciblée shop:gelato-resync {slug} {store_product_id} {--dry}. Fix gelato_product_id obsolète (gqa_classic/gpr_0-4 → gqa_heavy-weight/gpr_4-0). Fix vue show.blade.php : checkout hidden inputs variant_gelato_uid = product_uids[taille] (combo couleur+taille, bug pré-existant couleur-seule), variant_label inclut taille, variant_gelato_id ajouté. Résultat validé Playlright super admin : 9 dots hex exacts, 66 variants, 5XL = 29,99 $ surcharge OK. + #210 kill switch ShopMaintenanceMode (config shop.maintenance, bypass isSuperAdmin, JSON 503 AJAX / vue maintenance HTML 503, Octopus thinking). + #209 Concentré IA hebdo dimanche → lundi pour semaine précédente. + #208 jour newsletter Brain Dump dimanche → mercredi (cadence réelle).
 *   1.14.0 · 2026-05-13 · #206 refonte hero Brain Dump pour clarté 5 s (combo A+F sonar-pro 92/100). Tagline 24 mots vs 80, visuel SVG Before→After inline (papier manuscrit→bulle IA→liste actions cochables), 3 cards étapes numérotées (Écris/Photographie/Reçois), 1 CTA primary, signaux compacts, byline EEAT préservée. Fix sizing SVG via width/height attrs HTML + CSS !important (theme Bloggar override leçon S94). + #207 refonte section « Outils par profil » → « Quelle IA utiliser ? » (5 cards IA majeures ChatGPT/Claude/Gemini/Copilot/Perplexity, zéro app OCR tierce, philosophie force de l'IA directe). + #205 retire stat inventée « 86 % satisfaction abonnés » → « ⚡ 30 sec avec l'IA » (EEAT).
 *   1.13.0 · 2026-05-13 · #204 composant `<x-tools::octopus>` étendu 6 → 12 variants (compositions + émotions). `<x-core::empty-state>` enrichi prop `octopus` (remplace icône emoji). Search palette Cmd+K empty state initial = Octopus loved (« cherche pour vous »), no-results = Octopus confused (« n'a rien trouvé »). Consolidation 12 SVG dans Modules/Tools/resources/assets/octopus/ (dossier preview/ supprimé). #203 harmonisation 11 SVG aux tokens charte officielle (corps #0B7285 / tentacules #52B8C7 / pupilles #1a1d23 — intro.svg comme référence).
 *   1.12.0 · 2026-05-13 · #202 Octopus mascotte sur 7 pages erreur (403/404/405/419/429/500/503) — réutilisation stratégique post-désactivation quête. Partial paramétrisé errors.octopus._render avec 6 émotions SVG (4 nouvelles : confused/thinking/sleeping/surprised générées via qwen3-max openrouter-free 1.4s 0$ + 2 réservées happy/loved). Layout commun aux tokens charte officielle (#0B7285/#C2410C/#F8FAFB). Mapping par code : 404 confused, 403/503 thinking, 419/429 sleeping, 405 confused, 500 surprised. Microcopy ton FR-CA "Cette page s'est perdue dans les courants". + Désactivation /quete via QUEST_ENABLED=false (.env prod) + retrait liens menu (4 occurrences gated config('tools.quest.enabled')). Module préservé pour réactivation 1-flag.
 *   1.11.2 · 2026-05-13 · #189 fix charte /quete — chapter.blade.php + index.blade.php redéfinissaient des tokens locaux (--c-primary #064E5A / --c-accent #9A2A06 / --c-bg #F0F4F8) qui shadowaient les tokens charte officiels (#0B7285 / #C2410C / #F8FAFB). Refactor: héritage direct :root + --c-primary-hover + --c-primary-light + --c-primary-badge + --c-accent-light + --c-text-muted, fonts --f-heading (Plus Jakarta Sans) sur titres/chips/boutons + --f-body (DM Sans) sur corps, radius --r-base/--r-btn, focus-visible orange WCAG AAA SC 2.4.7. + redirect 301 /quete/ch1-eveil-loop → /quete/ch1-eveil-octopus + migration DB current_chapter.
 *   1.11.1 · 2026-05-13 · #189 réécriture ch1 narrative Loop → Octopus (cohérence mascotte) — pieuvre numérique 8 tentacules + clairière sous-marine + bulles-mots + tentacule lumineux. Concepts pédagogiques LLM/prédiction/hallucinations conservés. Délégation rédaction qwen3-max via openrouter-free.
 *   1.11.0 · 2026-05-13 · #201 Cmd+K command palette globale — modale Alpine WCAG (role=dialog + aria-modal + focus auto + return-focus) déclenchée par Cmd+K (macOS) / Ctrl+K (Windows/Linux) ou bouton loupe header, recherche live cross-module via endpoint JSON `/recherche/palette` (web throttle 60/min) servie par SearchService::searchFront() limité 6/section depuis SearchRegistry (Blog + Actualités + Glossaire + Annuaire + Acronymes), debounce 250 ms + AbortController, keyboard nav ↑↓/Enter/Esc, sections groupées avec icône+compteur, footer « Voir tous les résultats » → /recherche?q=, mobile fullscreen, modules désactivés ignorés (zéro régression). + #200 refonte menus navigation Option E hybride — 3 mega menus Outils (4 groupes Productivité/Création/Détente/Pratique) + Annuaire (5 fiches stars data-driven GA4) + Apprendre (Contenu éditorial + Référence) + mobile sidebar refondue.
 *   1.10.0 · 2026-05-12 · #198 Brain Dump Partie 2 — refonte Mad Libs C+E (90/100 best practice 2026) — 5 chips inline cliquables (catégories multi-select / nbPatterns / nbActions / horizon / tone) avec popovers Alpine, prompt copié = rendu actuel substituant variables, WCAG AAA 32-44px target sizes, mobile popover full-width. + #196 uniformité bloc tool charte Memora (card blanc + ct-btn teal) + #195 Octopus intro.svg lisible (corps #0B7285 + tentacules #52B8C7 + pupilles #1a1d23).
 *   1.9.0 · 2026-05-12 · #194 Brain Dump 2026 — page dédiée /outils/brain-dump SEO+AEO+GEO+EEAT (Schema SoftwareApplication+HowTo+FAQPage+BreadcrumbList+Person, byline auteur, 3 citations scientifiques avec DOI, TL;DR speakable, charte Memora tokens, outil actif timer 10min + 2 prompts copy/Open-in AI 6 IAs) + alias FR /outils/vide-cerveau → 301
 *   1.8.0 · 2026-05-12 · #193 Octopus Prompt Builder Open-in AI — 6 boutons ChatGPT/Claude/Gemini/Perplexity/Mistral/Copilot (URL ?q= pré-rempli, fallback copy+redirect Gemini) + #182 atelier newsletter JIT (steps→prompt→ressources) + chain prompting CoT trigger + justification. Zéro coût opérationnel, zéro données serveur, zéro Loi 25 risk.
 *   1.7.0 · 2026-05-12 · #181 Menu navigation refonte action-oriented — Catégories→Apprendre + Blog/Pages retirés (footer) + Jouer mega menu NEW (Quête narrative, Constructeur, Comparateur, Sudoku, Mots croisés, Raccourcisseur, Calculatrice taxes QC) + WCAG AAA aria-haspopup/expanded/role=menu + mobile sidebar refactorée
 *   1.6.0 · 2026-05-08 · News SEO/AEO/GEO 2026 R1-R7 — JsonLdService enrichi (NewsMediaOrganization + Person/Org author + isBasedOn + speakable + articleBody/wordCount/keywords/inLanguage/articleSection) + TL;DR aside Speakable + H2 PAA + AiSummary tldr/quote/key_stat/expert + news-sitemap.xml dédié 72h
 *   1.5.0 · 2026-05-08 · Pricing audit S89 — BrowserFetch UA Chrome+retry (#58) + PpSearch direct OpenRouter (#60) + screenshot config flag (#59)
 *   1.4.1 · 2026-05-08 · Fix #57 image cassée glossaire (helper dictionary_hero_image_url + fallback .webp/.png)
 *   1.4.0 · 2026-05-08 · Audit pricing multi-source consensus + Playwright screenshot + SLA tiered + page admin review
 *   1.3.0 · 2026-05-08 · UX ultra-intuitive : bouton textuel "+ Ajouter au comparateur" + onboarding tooltip + popover 2e sélection
 *   1.2.1 · 2026-05-08 · Fix CSS compare-toggle invisible (relocation @once vers compare-bar inclus partout)
 *   1.2.0 · 2026-05-08 · Card overlay selection state + circle checkbox 32x32 + floating bar adaptative count>=1
 *   1.1.2 · 2026-05-08 · Fix duplication section Tendance vs Populaires (DRY) + badge vues intégré
 *   1.1.1 · 2026-05-08 · Fix bounce your@example.com (config/health.php hardcoded)
 *   1.1.0 · 2026-05-08 · Comparateur refonte sticky thead + slider arrows + mismatch detection + 6 outils max
 *   1.0.0 · 2026-05-08 · Initial production release (comparateur multi-outils livré)
 */

return [
    'major' => 1,
    'minor' => 18,
    'patch' => 1,

    /**
     * Codename optionnel (nom de la release courante).
     * Vide ou null si pas de codename.
     */
    'codename' => 'fix-404-redirects',

    /**
     * Format du SemVer assemblé.
     * Lu via lv_version() dans app/Helpers/version.php.
     */
    'semver' => '1.18.1',
];
