<?php

declare(strict_types=1);

/**
 * @author  MEMORA solutions <info@memora.ca> (https://memora.solutions)
 *
 * @project laveille.ai
 *
 * Versioning SemVer 2.0.0 — https://semver.org
 *
 * Règles de bump (Conventional Commits) :
 *   feat:        -> MINOR (nouvelle fonctionnalité, rétro-compatible)
 *   fix:         -> PATCH (correction de bug, rétro-compatible)
 *   feat!: ou
 *   BREAKING:    -> MAJOR (casse rétro-compatibilité)
 *   chore/test/refactor/docs/style/ci -> pas de bump
 *
 * Historique :
 *   1.19.1 · 2026-05-19 · #240 fix WCAG 2.2 AAA hero comparateur homepage (`Modules/FrontTheme/resources/views/home.blade.php:367-415`, section `Comparez 6 outils IA côte à côte` flag screenshot user 2026-05-19 08:12). Audit `wcag_check_contrast` MCP : 4 violations ratios sur le gradient `linear-gradient(135deg, #064E5A 0%, #0B7285 100%)` — (a) eyebrow « NOUVEAU · 2026 » white opacity 0.85 sur #0B7285 = 4.51:1 (échoue AAA 7:1), (b) description white opacity 0.93 = 5.06:1 (échoue AAA 7:1), (c) chips translucides `rgba(255,255,255,0.18)` = 3.94:1 (échoue MÊME AA 4.5:1), (d) hover chips `rgba(255,255,255,0.28)` = 4.48:1 (échoue AA). Fix : (1) remplace gradient par solide `#064E5A` (token charte primary) → white pur sur #064E5A = 9.35:1 AAA garanti partout dans la card, (2) retire `opacity: 0.85` de l'eyebrow + bump 11px→12px lisibilité, (3) retire `opacity: 0.93` de la description + ajoute `color: #fff` explicite, (4) remplace `background: rgba(255,255,255,0.12)` du CTA secondaire « 21 collections » par `background: transparent` + border `1px → 2px solid #fff` (outline style préserve l'affordance), (5) chips bg `rgba(255,255,255,0.18) → transparent` + border `1px rgba(0.25) → 2px rgba(0.55)`, hover JS adapté pour manipuler `borderColor` + `textDecoration` (au lieu de `background` qui cassait le contraste), ajout handlers `onfocus`/`onblur` pour accessibilité clavier équivalent au mouseover. Bonus a11y : `color: #fff` explicite sur eyebrow + H2 + description (au lieu de hériter du parent) → résiste aux overrides downstream + facilite l'audit DevTools. Aucun changement DB. Aucun nouveau cron. Codename hero-wcag-aaa.
 *   1.19.0 · 2026-05-19 · #239 page de statut publique `/statut` via paquet `memora/statut` v0.1.2 (Packagist, repo memorasolutions/statut publié par user). Pipeline : `composer require memora/statut` → auto-discover `Memora\Statut\StatutServiceProvider` + façade `Statut` ; `php artisan vendor:publish --tag=statut-config` → `config/statut.php` publié ; 5 vars `.env` ajoutées (`STATUT_ROBOTALP_API_KEY` clé Robotalp `da77...` partagée comptes Memora + `STATUT_ROBOTALP_WORKSPACE_ID=364200` workspace laveille.ai + `STATUT_LAYOUT=fronttheme::layouts.master` layout public site + `STATUT_BRAND_NAME="La veille"` + `STATUT_BRAND_URL=https://laveille.ai`). Audit code-reviewer-fr délégué sur v0.1.0 a remonté 10 coquilles (2 bloquantes : rate-limit absent + branding defaults `'MEMORA solutions'`/`https://memora.solutions` hardcodés en config; 5 importantes : `IncidentDto::monitorId` fallback `0` invalide, `role="alert"` abusif sur cartes incidents anti-pattern WCAG, `Carbon::parse('')` silencieux retournant `now()`, `RobotalpProvider` leak body 401 si api_key vide, `MonitorStatus::label()` + `locale_default` morts ; 3 mineures : `guzzlehttp/guzzle` déclaré mais code utilise façade `Http`, `illuminate/http` non explicite, `$layout` controller injecté directement dans `@extends()` sans validation). User a publié v0.1.1 (10/10 fixes) puis v0.1.2 (fix régression introduite par fix #10 : regex `^[A-Za-z0-9._-]+$` rejetait `::` séparateur namespace Blade Laravel standard, cassant tout layout `package::view.name` comme `fronttheme::layouts.master` → HTTP 500 → patché en `^[A-Za-z0-9._:-]+$` côté `StatutController.php:40`). Smoke `curl https://laveilledestef.test/statut` HTTP 200 · 439 KB · 0.80 s · rendu FrontTheme correct (627 occurrences brand) · `<h1>Service status</h1>` · 0 stacktrace Ignition. Throttle `throttle:60,1` hérité du package (60 req/min/IP, protège API Robotalp). Cache provider TTL 60 s (config `STATUT_CACHE_TTL`). Provider singleton `MonitoringProvider::class` binding controller invokable + DTOs `readonly`. `.env.example` complété avec les 5 placeholders (clé API laissée vide, intégrateur doit la fournir). Aucun changement DB. Aucun nouveau cron. Aucun module nwidart créé (paquet vendor pur). Codename statut-page.
 *   1.18.4 · 2026-05-18 · #238 CWV quick wins mobile (PageSpeed 38-52 → cible 75+, LCP 8-11s → cible <2.5s). Trois axes : (LCP) preload first hero image homepage + above-fold article image via `<link rel=preload as=image fetchpriority=high>` dans `home.blade.php` push head + `Modules/FrontTheme/resources/views/blog/show.blade.php` push head ; ajout `fetchpriority="high" loading="eager" decoding="async"` sur premier `<img>` hero homepage + image LCP article blog/show ; ajout `loading="lazy" decoding="async"` explicite sur hero2/3/4 homepage ; (TTFB) extension coverage Spatie ResponseCache aux routes publiques GET manquantes — `Modules/Directory/routes/web.php` (collections.index/show 600s, directory.index 600s, education-pricing 3600s, compare 600s, roadmap 3600s ; `directory.show` conserve doNotCacheResponse car personnalisé selon auth) ; `Modules/Tools/routes/web.php` (tools.index 600s, tools.show 600s) ; `Modules/Dictionary/routes/web.php` (dictionary.index/show 3600s — termes peu mutants) ; `Modules/News/routes/web.php` (news.index/show 600s). Cache home+blog déjà actifs S précédente (600s). (JS unused 7.2s) Master layout `Modules/FrontTheme/resources/views/layouts/master.blade.php` : ajout `defer` sur jQuery 3.7.1 + bootstrap.bundle + modernizr + dlmenu + jquery-plugin-collection + script.js (ordre exécution DOM-ready préservé via defer — défilement Alpine.js déjà defer). CSS bootstrap.min.css passé en pattern `preload+onload=rel=stylesheet` (async non-blocking) + `<noscript>` fallback. Compression `public/.htaccess` : DEFLATE coverage étendu (text/plain + text/javascript + application/x-javascript + application/ld+json + application/xhtml+xml + application/atom+xml + application/manifest+json + font/woff + font/woff2 + image/x-icon) + bloc `mod_brotli.c` ajouté (silencieusement ignoré si module absent, gain compression ~15-20% vs gzip si dispo Apache 2.4+). Fix bloqueur tests preexistant : `Modules/CloudflareCache/app/Jobs/PurgeCloudflareCacheJob.php` retire incompat `public string $queue` (typed) → `public $queue` (untyped) car trait `Illuminate\Bus\Queueable` déclare propriété non-typée — débloque suite Pest. Aucun changement DB. Aucun nouveau cron. Tokens charte Memora WCAG inchangé. Codename cwv-quick-wins.
 *   1.18.3 · 2026-05-18 · #237 P27 fix CRITIQUE Blade @context corruption JSON-LD glossaire + harmonisation Person author Schema.org. Cause racine : Laravel 11 a introduit la directive Blade `@context` qui intercepte toute occurrence de `@context` dans le source `.blade.php`, MÊME à l'intérieur d'une string PHP passée à `json_encode()` via `{!! !!}`. Le compilateur Blade remplace alors `@context` par du PHP (`context()->has(...)`) → JSON-LD rendu corrompu côté client → Google rejette le schema → perte rich snippets sur toutes pages avec glossaire actif (linkifier tooltips). Fix systémique : (a) `Modules/Core/resources/views/partials/glossary-jsonld.blade.php` — déplace le `json_encode([... '@context' ...])` du `{!! !!}` brut vers un bloc `@php { ... } @endphp` qui pré-encode dans `$__glossaryJsonLd`, puis `{!! $__glossaryJsonLd !!}` (Blade ne compile pas `@context` dans `@php`) ; (b) idem `Modules/Tools/resources/views/public/tools/crossword/index.blade.php` (CollectionPage JSON-LD) ; (c) `Modules/FrontTheme/resources/views/blog/show.blade.php` — clean le hack `chr(64).'context'` du FAQPage block (moved into `@php`) + clean le BlogPosting `chr(64).'context'` (moved to clean `'@context'` dans `@php`). Helper canonique créé : `app/Helpers/jsonld.php` avec `lv_jsonld_author_stephane()` (Person `@id` stable `https://laveille.ai/auteur/stephane-lapointe#person`, accents préservés « Stéphane », `sameAs` LinkedIn + MEMORA, `knowsAbout` 7 entrées EEAT incluant « Loi 25 (Québec) » / « RGPD » / « AI Act ») + `lv_jsonld_publisher()` Organization canonique. Helper autoloadé via `composer.json` `autoload.files[]` + `AppServiceProvider::register()` `require_once` (double layer prod-safe pattern P22). Refactor `Modules/SEO/app/Services/JsonLdService.php` : méthodes `article()` + `newsArticle()` utilisent maintenant `function_exists('lv_jsonld_author_stephane') ? lv_jsonld_author_stephane() : [fallback legacy]` pour harmoniser les BlogPosting/Article/NewsArticle author cross-vues (avant: "La veille" / "Stephane" sans accent / nom user brut, après: Person canonique consistant). Refactor `blog/show.blade.php` Article schema utilise aussi le helper. Validation Blade compiler local : 0 corruption signature `$__contextArgs` détectée dans les 3 fichiers patchés. 8 tests Pest reflexifs `Modules/SEO/tests/Feature/JsonLdGlossaryRenderTest.php` (44 assertions, 4.03s) : helper Person/Organization shape + compilation 7 fichiers blade sans corruption + glossary-jsonld preserve `@context` literal + blog/show no longer uses chr(64) workaround + JsonLdService uses helper + rendered JSON-LD via Blade is valid decodable + composer autoload registers jsonld.php. Zéro régression suite SEO complète : 44 tests verts / 142 assertions / 22.91s. Codename jsonld-context-fix.
 *   1.18.2 · 2026-05-18 · #236 P24 fix brand SEO « veille ai » (query GSC rank 15 alors que CTR 28.57 % = brand intent confirmé). Enrichissement Schema.org `JsonLdService::website()` + `organization()` dans Modules/SEO/app/Services/JsonLdService.php : (a) WebSite gagne `@id` `#website`, `alternateName` 4 variants (« La veille de Stef », « La veille IA », « Veille IA Québec », « veille ai » lowercase pour matcher la query exacte GSC), `description` enrichie Stéphane Lapointe + Loi 25 + concentrés hebdo (~200 chars optimal 2026), `inLanguage` fr-CA, `publisher` Organization (référence circulaire `@id` pour signal éditeur unique), SearchAction refondu en `EntryPoint` `urlTemplate` `/recherche?q={search_term_string}` (route réelle Modules/Search/routes/web.php — sitelinks searchbox Google) ; (b) Organization gagne `@id` `#organization`, `alternateName` 3 variants, `description` alignée WebSite, `areaServed` `[CA-QC, CA, FR]`, `inLanguage` fr-CA, accents restaurés (« Stéphane » vs « Stephane »), `sameAs` ajout `https://memora.solutions` en complément LinkedIn auteur + Facebook. (c) Title homepage `Modules/FrontTheme/resources/views/home.blade.php` accents restaurés (« numérique » + « Québec » vs ASCII), séparateur passé à em-dash « — » cohérent avec H1, meta_description remplacée par version optimisée 200 chars incluant « Veille IA au Québec », « Stéphane Lapointe », « Loi 25 », « concentrés hebdomadaires », « organisations francophones » (mots-clés brand+contexte+EEAT). 6 tests Pest reflexifs verts (29 assertions) sur `JsonLdService::website()` + `organization()` + `render()` : alternateName presence + SearchAction EntryPoint shape + inLanguage fr-CA + publisher Organization + sameAs LinkedIn Stéphane + render output contient « veille ai » / « SearchAction » / « lapointestephane » pour crawlers Googlebot/Bingbot/Perplexity. Zéro régression Pest suite SEO complète 36 verts / 98 assertions. Codename brand-seo-fix.
 *   1.18.1 · 2026-05-18 · #235 P17 fix 404 prod actionnables : (a) redirects 301 sitemaps legacy bots `/sitemap_index.xml` + `/sitemaps.xml` + `/sitemap.xml.gz` + `/atom.xml` → `/sitemap.xml` via Route::redirect inline dans Modules/SEO/routes/web.php (DRY natif Laravel) ; (b) wildcard `/outil/{slug?}` (typo singular legacy WP) → smart redirect 301 vers `/outils/{slug}` si Tool::where('slug')->exists() sinon `/outils` (closure inline dans Modules/Tools/routes/web.php, regex `[a-z0-9\-]*` accepte vide aussi) ; (c) `/actualites/{slug}` refondu en closure smart : NewsArticle::where('slug')->first() → si trouvé délègue PublicNewsController::show(article), sinon 301 vers `/actualites` (Modules/News/routes/web.php — remplace ancien route model binding qui throwait 404 sur slugs orphelins) ; (d) `/auteur/{slug}/page/{n}` legacy WordPress pagination → 301 vers `/auteur/{slug}` (auteur unique <10 articles, pagination inutile) dans Modules/FrontTheme/routes/web.php ; (e) JS stubs `/js/ga4-events.js` + `/js/sw-register.js` + `/sw.js` déjà 200 OK prod (false 404 dans rapport user). 9 tests Pest reflexifs verts (14 assertions, route inspection pattern pour éviter SQLite settings bloqueur). Codename fix-404-redirects.
 *   1.18.0 · 2026-05-18 · #234 EEAT byline + page auteur Stéphane Lapointe activée (matériel user fourni) — 5 photos optimisées (webp+jpg 80/256 + schema 1200), bio mise à jour avec livre « L'IA sans se faire poursuivre » Édition 2026 + 20+ ans gouvernance numérique + L'Ancienne-Lorette QC, LinkedIn `https://www.linkedin.com/in/lapointestephane` (rel="me" IndieWeb critique), 4 qualifications (Fondateur MEMORA / Auteur livre 2026 / Expert 20+ ans / Spécialiste Loi 25+RGPD+AI Act), 7 entrées knowsAbout Schema.org Person, H1 "Nom — Rôle" pour signal expertise immédiat, picture webp+jpg fallback responsive, byline cards et author-box bottom blog/show utilisent photo réelle (vs logo-avatar générique), AuthorController enrichi (@id, knowsAbout, image dédiée file_exists fallback, limit 10 articles), réutilise composant DRY `<x-fronttheme::book-promo>` sur page auteur, 14 nouveaux tests Pest reflexifs AuthorPageTest + 3 enrichis AuthorsTranslationTest (27 verts / 61 assertions total). Sitemap.xml + link rel="author" master layout + meta name="author" déjà cablés depuis S84 scaffolding. Codename eeat-stephane-active.
 *   1.17.2 · 2026-05-18 · #232 désactive temporairement /annuaire/classement (1 seul contributor solo, classement vide d'intérêt). Feature flag réversible `directory.leaderboard.enabled` (default false, env DIRECTORY_LEADERBOARD_ENABLED) dans Modules/Directory/config/config.php (pattern réutilisé de `category_alerts`). Route /annuaire/classement conservée mais wrappée dans closure qui redirige 302 vers /annuaire avec flash session `info` ("Le classement sera disponible quand plusieurs contributeurs participeront à l'annuaire.") quand flag off ; déléguée à `app(LeaderboardController::class)->index()` quand flag on. Nom de route `directory.leaderboard` préservé pour que `Route::has()` reste vrai et que les gates @if combinent Route::has + config flag (double sécurité, traçabilité). 5 gates @if mis à jour dans header.blade.php (4 = mega-menu desktop + 2 sub-menu mobile + offcanvas mobile) + 1 gate dans footer.blade.php. Pour réactiver dès que ≥3 contributeurs réguliers : DIRECTORY_LEADERBOARD_ENABLED=true (.env prod) — pas besoin de redéployer. 6 tests Pest verts (15 assertions) — reflexifs source-based pour éviter dépendance DB lourde (closure inline + nom route + gates + config default). Sitemap.xml vérifié zéro référence préalable (jamais référencé). Codename leaderboard-feature-flag.
 *   1.17.1 · 2026-05-18 · #231 NBSP typographie FR site-wide — helper `lv_typo_fr()` autoload via composer.json `files[]` + `app/Providers/AppServiceProvider::register()` (idempotent, double layer prod-safe). Directive Blade `@typo($text)` + macro `Str::typoFr()` enregistrées dans `boot()`. Règles appliquées : (1) NBSP avant `? ! : ; »` (ponctuation double FR) ; (2) NBSP après `«` (guillemet ouvrant) ; (3) NBSP entre chiffre et unité (`%`, `$`, `€`, `°C`, `M$`, `M€`, `k€`, `k$`). Préservation 3 couches : (a) URL — pas de NBSP injecté dans `href="...?q=1"` ; (b) HTML — segmentation balises `<...>` / texte, balises laissées intactes ; (c) JSON — détection auto `{...}` ou `[...]`, walk récursif sur valeurs string uniquement, ré-encode JSON valide (préserve colonnes spatie/laravel-translatable `{"fr_CA":"..."}`). 19 tests Pest verts (40 assertions). Patch composant `<x-fronttheme::book-promo>` user-visible (title/subtitle/descriptions) → fix bug screenshot user `?` rejeté + `7\n%` séparés. Command Artisan `php artisan typo:apply-fr {--dry} {--table=*}` idempotente avec plan curated 8 tables (articles, ads_placements, directory_tools, dictionary_terms, news_articles, pages, faqs, testimonials). Codename typo-fr-nbsp.
 *   1.17.0 · 2026-05-18 · #230 remplace pub Nexus Neural par livre auteur « L'IA sans se faire poursuivre : guide pratique pour PME et professionnels — Édition 2026 ». Composant Blade réutilisable `<x-fronttheme::book-promo>` (DRY) avec 20 props (title/subtitle/author/cover_url_webp/cover_url_jpg/cta_url/schema/variant/etc.). Schema.org Book JSON-LD complet (Person Stéphane Lapointe + Organization MEMORA solutions + Offer Amazon CAD). WCAG 2.2 AA (min-height 44px CTA, focus-visible orange #C2410C, alt SEO descriptif Loi 25/RGPD/AI Act/PME). 4 images optimisées dans `public/images/books/` : webp 600 ~52KB, jpg 600 ~121KB (fallback compat réseaux sociaux), webp 300 ~21KB (mobile thumbnail), og 1200×630 ~54KB (Facebook/LinkedIn/Twitter cards). Responsive flex-row desktop / flex-column mobile <640px. Alpine.js x-collapse description longue toggle. CTA target=_blank + rel="noopener sponsored". Enhancement `AdsRenderer::render()` détecte `<x-` dans `ad_code` et compile via `Blade::render()` (pattern réutilisable pour toute pub à base de composant). DB ads : id=1 renommé `nexus-neural` → `book-author`, id=2 `article-inline` (auto-injection après 3e paragraphe articles) — les 2 utilisent `<x-fronttheme::book-promo variant="inline" />`. Migration `2026_05_18_120000_replace_nexus_neural_ads_with_book_promo.php` propage le changement DB en prod. 11 tests Pest verts (28 assertions). Codename book-promo-component.
 *   1.16.2 · 2026-05-18 · #229 fix popup newsletter /blog — bouton fermeture 14×26 → 44×44 px (WCAG 2.5.5 AAA) + cible touch mobile fiable + ESC handler explicite (delegation $(document)) + click backdrop ferme + data-bs-dismiss="modal" fallback Bootstrap natif + delegation click closeBtn (résiste au re-render DOM) + modal-dialog-scrollable + max-height calc(100vh - 40px) + overflow-y:auto !important sur modal-content (fix Bootstrap 5.0.1 cascade qui forçait overflow:hidden) + box-sizing:border-box inputs + font-size 16px (anti-zoom iOS) + media query mobile <480px margin/max-width adaptés. Cause racine confirmée Playwright prod 375×667 : modal débordait bottom 672>667, X 14×26 inatteignable touch, modal-content computed overflow:hidden empêchait scroll vers champs/consent/submit. Codename popup-newsletter-fix.
 *   1.16.1 · 2026-05-18 · #227 fix migration JSON_UNQUOTE compat SQLite — wrap `if (DB::getDriverName() === 'mysql')` autour des statements MySQL-only dans Modules/Dictionary/database/migrations/2026_05_05_180100_set_transformer_case_sensitive.php (up + down). Débloque Pest local (SQLite in-memory) qui plantait sur JSON_UNQUOTE/JSON_EXTRACT inexistants en SQLite. Aucun impact prod (MySQL exécute toujours la data migration originelle). Codename pest-sqlite-unblocked.
 *   1.16.0 · 2026-05-18 · #226 unsubscribe v2 — refonte complète flux désabonnement newsletter. Migration colonnes dédiées (unsubscribe_token, unsubscribed_at, unsubscribe_reason). Vue dédiée avec confirmation + raison optionnelle + routes web sécurisées par token signé. Tests Pest couvrant nominal/expired/invalid/double-click. Codename unsubscribe-v2.
 *   1.15.2 · 2026-05-17 · #226 fix assets admin post-login — retrait `splash-screen.css` orphelin (CSS jamais déployé, 404 console) dans Modules/Auth/resources/views/layouts/app.blade.php + Modules/Backoffice/resources/views/themes/backend/layouts/admin.blade.php + retrait blocs JS dynamiques associés (createElement splash). Standardisation `apexcharts.min.js` sur CDN jsdelivr v4.4.0 (cohérence stats/index.blade.php S89) dans dashboard/index.blade.php + revenue/index.blade.php (élimine asset local manquant). Codename admin-assets-fix. Console admin propre post-login user S95.
 *   1.15.1 · 2026-05-17 · #225 fix login bloqué — retrait `<script src="auth/plugins/preline/preline.js">` orphelin (404 console, fichier jamais déployé) dans Modules/Auth/resources/views/layouts/guest.blade.php + ajout `<meta name="mobile-web-app-capable" content="yes">` (deprecation warning Chrome, apple-mobile-web-app-capable conservé pour compat iOS Safari). Codename login-fix. Bloqueur user signalé S95 ; 415 Livewire résolu en parallèle via purge Cloudflare cache.
 *   1.15.0 · 2026-05-14 · #211 Boutique Phase 1 — audit t-shirt Gelato + correction désync majeure. Migration colonnes dédiées (gelato_store_product_id varchar 64 indexé, legacy_gelato_uid backup, gelato_synced_at). GelatoSyncService (fetch store API ecommerce.gelatoapis.com + transformToLocalVariants : 9 couleurs Gildan 5000 hex, size_prices avec SIZE_SURCHARGE 2XL+3/3XL+5/4XL+7/5XL+9, variant_ids + product_uids par taille). Command ciblée shop:gelato-resync {slug} {store_product_id} {--dry}. Fix gelato_product_id obsolète (gqa_classic/gpr_0-4 → gqa_heavy-weight/gpr_4-0). Fix vue show.blade.php : checkout hidden inputs variant_gelato_uid = product_uids[taille] (combo couleur+taille, bug pré-existant couleur-seule), variant_label inclut taille, variant_gelato_id ajouté. Résultat validé Playlright super admin : 9 dots hex exacts, 66 variants, 5XL = 29,99 $ surcharge OK. + #210 kill switch ShopMaintenanceMode (config shop.maintenance, bypass isSuperAdmin, JSON 503 AJAX / vue maintenance HTML 503, Octopus thinking). + #209 Concentré IA hebdo dimanche → lundi pour semaine précédente. + #208 jour newsletter Brain Dump dimanche → mercredi (cadence réelle).
 *   1.14.0 · 2026-05-13 · #206 refonte hero Brain Dump pour clarté 5 s (combo A+F sonar-pro 92/100). Tagline 24 mots vs 80, visuel SVG Before→After inline (papier manuscrit→bulle IA→liste actions cochables), 3 cards étapes numérotées (Écris/Photographie/Reçois), 1 CTA primary, signaux compacts, byline EEAT préservée. Fix sizing SVG via width/height attrs HTML + CSS !important (theme Bloggar override leçon S94). + #207 refonte section « Outils par profil » → « Quelle IA utiliser ? » (5 cards IA majeures ChatGPT/Claude/Gemini/Copilot/Perplexity, zéro app OCR tierce, philosophie force de l'IA directe). + #205 retire stat inventée « 86 % satisfaction abonnés » → « ⚡ 30 sec avec l'IA » (EEAT).
 *   1.13.0 · 2026-05-13 · #204 composant `<x-tools::octopus>` étendu 6 → 12 variants (compositions + émotions). `<x-core::empty-state>` enrichi prop `octopus` (remplace icône emoji). Search palette Cmd+K empty state initial = Octopus loved (« cherche pour vous »), no-results = Octopus confused (« n'a rien trouvé »). Consolidation 12 SVG dans Modules/Tools/resources/assets/octopus/ (dossier preview/ supprimé). #203 harmonisation 11 SVG aux tokens charte officielle (corps #0B7285 / tentacules #52B8C7 / pupilles #1a1d23 — intro.svg comme référence).
 *   1.12.0 · 2026-05-13 · #202 Octopus mascotte sur 7 pages erreur (403/404/405/419/429/500/503) — réutilisation stratégique post-désactivation quête. Partial paramétrisé errors.octopus._render avec 6 émotions SVG (4 nouvelles : confused/thinking/sleeping/surprised générées via qwen3-max openrouter-free 1.4s 0$ + 2 réservées happy/loved). Layout commun aux tokens charte officielle (#0B7285/#C2410C/#F8FAFB). Mapping par code : 404 confused, 403/503 thinking, 419/429 sleeping, 405 confused, 500 surprised. Microcopy ton FR-CA "Cette page s'est perdue dans les courants". + Désactivation /quete via QUEST_ENABLED=false (.env prod) + retrait liens menu (4 occurrences gated config('tools.quest.enabled')). Module préservé pour réactivation 1-flag.
 *   1.11.2 · 2026-05-13 · #189 fix charte /quete — chapter.blade.php + index.blade.php redéfinissaient des tokens locaux (--c-primary #064E5A / --c-accent #9A2A06 / --c-bg #F0F4F8) qui shadowaient les tokens charte officiels (#0B7285 / #C2410C / #F8FAFB). Refactor: héritage direct :root + --c-primary-hover + --c-primary-light + --c-primary-badge + --c-accent-light + --c-text-muted, fonts --f-heading (Plus Jakarta Sans) sur titres/chips/boutons + --f-body (DM Sans) sur corps, radius --r-base/--r-btn, focus-visible orange WCAG AAA SC 2.4.7. + redirect 301 /quete/ch1-eveil-loop → /quete/ch1-eveil-octopus + migration DB current_chapter.
 *   1.11.1 · 2026-05-13 · #189 réécriture ch1 narrative Loop → Octopus (cohérence mascotte) — pieuvre numérique 8 tentacules + clairière sous-marine + bulles-mots + tentacule lumineux. Concepts pédagogiques LLM/prédiction/hallucinations conservés. Délégation rédaction qwen3-max via openrouter-free.
 *   1.11.0 · 2026-05-13 · #201 Cmd+K command palette globale — modale Alpine WCAG (role=dialog + aria-modal + focus auto + return-focus) déclenchée par Cmd+K (macOS) / Ctrl+K (Windows/Linux) ou bouton loupe header, recherche live cross-module via endpoint JSON `/recherche/palette` (web throttle 60/min) servie par SearchService::searchFront() limité 6/section depuis SearchRegistry (Blog + Actualités + Glossaire + Annuaire + Acronymes), debounce 250 ms + AbortController, keyboard nav ↑↓/Enter/Esc, sections groupées avec icône+compteur, footer « Voir tous les résultats » → /recherche?q=, mobile fullscreen, modules désactivés ignorés (zéro régression). + #200 refonte menus navigation Option E hybride — 3 mega menus Outils (4 groupes Productivité/Création/Détente/Pratique) + Annuaire (5 fiches stars data-driven GA4) + Apprendre (Contenu éditorial + Référence) + mobile sidebar refondue.
 *   1.10.0 · 2026-05-12 · #198 Brain Dump Partie 2 — refonte Mad Libs C+E (90/100 best practice 2026) — 5 chips inline cliquables (catégories multi-select / nbPatterns / nbActions / horizon / tone) avec popovers Alpine, prompt copié = rendu actuel substituant variables, WCAG AAA 32-44px target sizes, mobile popover full-width. + #196 uniformité bloc tool charte Memora (card blanc + ct-btn teal) + #195 Octopus intro.svg lisible (corps #0B7285 + tentacules #52B8C7 + pupilles #1a1d23).
 *   1.9.0 · 2026-05-12 · #194 Brain Dump 2026 — page dédiée /outils/brain-dump SEO+AEO+GEO+EEAT (Schema SoftwareApplication+HowTo+FAQPage+BreadcrumbList+Person, byline auteur, 3 citations scientifiques avec DOI, TL;DR speakable, charte Memora tokens, outil actif timer 10min + 2 prompts copy/Open-in AI 6 IAs) + alias FR /outils/vide-cerveau → 301
 *   1.8.0 · 2026-05-12 · #193 Octopus Prompt Builder Open-in AI — 6 boutons ChatGPT/Claude/Gemini/Perplexity/Mistral/Copilot (URL ?q= pré-rempli, fallback copy+redirect Gemini) + #182 atelier newsletter JIT (steps→prompt→ressources) + chain prompting CoT trigger + justification. Zéro coût opérationnel, zéro données serveur, zéro Loi 25 risk.
 *   1.7.0 · 2026-05-12 · #181 Menu navigation refonte action-oriented — Catégories→Apprendre + Blog/Pages retirés (footer) + Jouer mega menu NEW (Quête narrative, Constructeur, Comparateur, Sudoku, Mots croisés, Raccourcisseur, Calculatrice taxes QC) + WCAG AAA aria-haspopup/expanded/role=menu + mobile sidebar refactorée
 *   1.6.0 · 2026-05-08 · News SEO/AEO/GEO 2026 R1-R7 — JsonLdService enrichi (NewsMediaOrganization + Person/Org author + isBasedOn + speakable + articleBody/wordCount/keywords/inLanguage/articleSection) + TL;DR aside Speakable + H2 PAA + AiSummary tldr/quote/key_stat/expert + news-sitemap.xml dédié 72h
 *   1.5.0 · 2026-05-08 · Pricing audit S89 — BrowserFetch UA Chrome+retry (#58) + PpSearch direct OpenRouter (#60) + screenshot config flag (#59)
 *   1.4.1 · 2026-05-08 · Fix #57 image cassée glossaire (helper dictionary_hero_image_url + fallback .webp/.png)
 *   1.4.0 · 2026-05-08 · Audit pricing multi-source consensus + Playwright screenshot + SLA tiered + page admin review
 *   1.3.0 · 2026-05-08 · UX ultra-intuitive : bouton textuel "+ Ajouter au comparateur" + onboarding tooltip + popover 2e sélection
 *   1.2.1 · 2026-05-08 · Fix CSS compare-toggle invisible (relocation @once vers compare-bar inclus partout)
 *   1.2.0 · 2026-05-08 · Card overlay selection state + circle checkbox 32x32 + floating bar adaptative count>=1
 *   1.1.2 · 2026-05-08 · Fix duplication section Tendance vs Populaires (DRY) + badge vues intégré
 *   1.1.1 · 2026-05-08 · Fix bounce your@example.com (config/health.php hardcoded)
 *   1.1.0 · 2026-05-08 · Comparateur refonte sticky thead + slider arrows + mismatch detection + 6 outils max
 *   1.0.0 · 2026-05-08 · Initial production release (comparateur multi-outils livré)
 */

return [
    'major' => 1,
    'minor' => 19,
    'patch' => 1,

    /**
     * Codename optionnel (nom de la release courante).
     * Vide ou null si pas de codename.
     */
    'codename' => 'cwv-quick-wins',

    /**
     * Format du SemVer assemblé.
     * Lu via lv_version() dans app/Helpers/version.php.
     */
    'semver' => '1.18.4',
];
