<?php

declare(strict_types=1);

namespace Database\Seeders\Standalone;

use Illuminate\Database\Seeder;
use Modules\Blog\Models\Article;
use Modules\Blog\Models\Category;
use Modules\Blog\States\PublishedArticleState;
use App\Models\User;

class ConcentreHebdo20260629Seeder extends Seeder
{
    public function run(): void
    {
        $slug = 'concentre-ia-semaine-29-5-juillet-2026';

        if (Article::whereJsonContains('slug->fr_CA', $slug)->exists()) {
            $this->command?->info('Article déjà existant, skip.');
            return;
        }

        $title = 'Concentré IA - semaine du 29 juin au 5 juillet 2026';

        $excerpt = "Anthropic multiplie les annonces (Fable 5, Claude Sonnet 5, Claude Science), Google consolide Gemini partout (Meet, Gmail, NotebookLM, Renault), pendant que régulation et marché de l'IA s'intensifient. Le concentré de la semaine du 29 juin au 5 juillet 2026.";
        $metaDescription = "Concentré IA de la semaine du 29 juin au 5 juillet 2026 : Claude Sonnet 5, Fable 5, Gemini partout chez Google, régulation santé et éducation par IA.";
        $seoTitle = 'Concentré IA semaine du 29 juin au 5 juillet 2026 - laveille.ai';

        $content = <<<'HTML'
<p><strong>Introduction :</strong> La semaine du 29 juin au 5 juillet 2026 a été marquée par trois mouvements de fond. D'abord, l'écosystème Anthropic a multiplié les annonces, entre bannissement et retour de Fable 5, nouveau Claude Sonnet 5 agentique et incursion dans la découverte de médicaments suivie de près par le MILA et IVADO. Ensuite, Google a consolidé Gemini dans le quotidien numérique, de NotebookLM à Google Meet en passant par l'automobile avec Renault. Enfin, les tensions réglementaires se sont multipliées : protection des données de santé qui fait écho à la Loi 25 québécoise, éducation privée par IA et litige entre Midjourney et Hollywood. Voici un concentré des développements les plus significatifs de la semaine.</p>

<h2 id="1-alibaba-interdit-claude-code-a-ses-employes">1. Alibaba interdit Claude Code à ses employés</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 4 juillet 2026</p>
<p itemprop="text">Le 4 juillet 2026, <strong>Alibaba</strong> a annoncé l'interdiction, dès le 10 juillet, de l'usage de Claude Code d'Anthropic par ses employés, classant l'outil comme logiciel à haut risque et imposant son alternative maison Qoder. Anthropic bloque déjà l'accès de ses modèles aux entreprises chinoises et à leurs filiales étrangères ; une version antérieure de Claude Code pouvait secrètement identifier les utilisateurs chinois, une mesure présentée par Anthropic comme un dispositif anti-abus visant les revendeurs non autorisés et la distillation de modèles. Ce bras de fer illustre la fragmentation croissante de l'accès aux outils d'IA générative selon les frontières géopolitiques. Pour les entreprises technologiques d'ici qui collaborent avec des partenaires asiatiques, l'épisode rappelle que le choix d'un outil de développement assisté par IA est désormais aussi une question de conformité géopolitique que de performance technique. <a href="/actualites/alibaba-reportedly-bans-employees-from-using-claude-code">Lecture complète</a>.</p>

<h2 id="2-anthropic-partage-ses-conseils-de-prompt-pour-fable-5">2. Anthropic partage ses conseils de prompt pour Fable 5</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 4 juillet 2026</p>
<p itemprop="text">Le 4 juillet 2026, Thariq Shihipar, développeur chez <strong>Anthropic</strong>, a publié une méthode pour améliorer les invites destinées à Fable 5 en repérant d'abord ses propres angles morts, les « unknown unknowns », avant de coder quoi que ce soit. Il recommande notamment un exercice appelé le « blindspot pass » ainsi que la génération de prototypes jetables pour révéler les hypothèses implicites d'un projet avant l'implémentation définitive. Selon lui, ignorer ces angles morts mène à l'échec dans les deux sens : soit le modèle comble le vide à sa manière, soit l'utilisateur découvre trop tard qu'il avait mal cadré le problème. Pour les équipes techniques qui adoptent des assistants conversationnels au quotidien, cette approche structurée de la préparation du prompt rappelle qu'un cadrage rigoureux en amont demeure la variable la plus déterminante de la qualité des résultats obtenus. <a href="/actualites/anthropic-developer-shares-prompting-tips-for-fable-5-that-focus-on-finding-your-own-blind-spots-first">Analyse complète</a>.</p>

<h2 id="3-la-communaute-de-fanfiction-se-dechire-sur-la-detection-de-lia">3. La communauté de fanfiction se déchire sur la détection de l'IA</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 4 juillet 2026</p>
<p itemprop="text">Le 4 juillet 2026, une extension de navigateur destinée au site de fanfiction Archive of Our Own (AO3) a commencé à circuler, prétendant détecter les textes générés par <strong>Claude</strong> grâce à un artefact de code laissé lorsque la réponse est copiée directement depuis l'interface d'Anthropic. Le fond de la page devient rouge lorsque l'extension croit reconnaître ce marqueur, mais la méthode ne fonctionne que dans ce cas précis de copier-coller brut, laissant passer tout texte simplement retouché. Une partie de la communauté dénonce déjà publiquement des auteurs sur la seule foi de cet indice fragile, ce qui multiplie les faux positifs et les accusations mal fondées. L'épisode illustre un problème plus large : la détection de contenu généré par IA reste une science imparfaite, un rappel utile pour toute organisation qui envisagerait d'imposer une politique de divulgation obligatoire de l'usage de l'IA dans ses contenus. <a href="/actualites/the-fanfiction-community-is-at-war-with-ai-and-itself">Détails sur la fiche</a>.</p>

<h2 id="4-anthropic-lance-ses-propres-programmes-de-decouverte-de-medicaments">4. Anthropic lance ses propres programmes de découverte de médicaments</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 4 juillet 2026</p>
<p itemprop="text">Le 4 juillet 2026, <strong>Anthropic</strong> a dévoilé des programmes internes de découverte de médicaments ciblant des maladies négligées par l'industrie pharmaceutique traditionnelle, jugées peu rentables par les grands laboratoires. L'entreprise s'appuie sur son outil Claude Science pour accélérer la recherche préclinique ; dans un exemple cité, le système a analysé une centaine de maladies génétiques rares en moins d'une heure afin d'identifier des candidats médicaments potentiels. Anthropic présente cette initiative comme cohérente avec sa mission à but non lucratif, tout en reconnaissant qu'elle lui permettra aussi d'améliorer ses propres modèles grâce à une expérience de terrain concrète en recherche biomédicale. Les chercheurs du MILA et d'IVADO suivent avec attention ce type de convergence entre laboratoires d'IA générale et recherche biomédicale appliquée, un axe où le Québec possède déjà une expertise reconnue en apprentissage automatique pour les sciences de la vie. <a href="/actualites/anthropic-launches-its-own-drug-discovery-programs-to-tackle-diseases-big-pharma-considers-unprofitable">Voir le contexte</a>.</p>

<h2 id="5-un-modele-affine-surpasse-gpt-et-claude-en-finance">5. Un modèle affiné surpasse GPT et Claude en finance</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 3 juillet 2026</p>
<p itemprop="text">Le 3 juillet 2026, <strong>Bridgewater</strong> et Thinking Machines Lab, la jeune pousse cofondée par l'ex-directrice technique d'OpenAI Mira Murati, ont publié les résultats d'un modèle open-weight affiné sur des données financières propriétaires. Ce modèle atteint <strong>84,7 %</strong> de précision dans l'évaluation de jugements financiers, contre seulement 78,2 % pour le meilleur modèle commercial testé et à peine 50 % pour GPT, Claude et Gemini soumis à une invite basique sans affinage. Le coût d'exécution du modèle spécialisé est par ailleurs <strong>14 fois inférieur</strong> à celui des modèles commerciaux équivalents. Les auteurs précisent que les investisseurs humains n'ont corrigé que les cas où le modèle et les étiquettes d'origine étaient en désaccord, une méthode d'annotation ciblée qui réduit l'effort humain requis. Pour les institutions financières d'ici, la démonstration confirme qu'un affinage sur données propriétaires peut surpasser les modèles généralistes sans dépendre entièrement d'un fournisseur externe. <a href="/actualites/gpt-and-claude-failed-bridgewaters-finance-tests-because-the-right-answers-were-never-public">Décryptage</a>.</p>

<h2 id="6-fable-5-de-retour-dans-le-monde-entier-apres-un-bannissement">6. Fable 5 de retour dans le monde entier après un bannissement</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 1 juillet 2026</p>
<p itemprop="text">Le 1er juillet 2026, <strong>Anthropic</strong> a annoncé la remise en service mondiale de Fable 5 après un bannissement de deux semaines imposé par le gouvernement américain, à la suite de la découverte d'une faille de sécurité par des chercheurs d'Amazon. Cette faille permettait de contourner certaines protections du modèle par une technique de contournement (jailbreak). Anthropic affirme avoir renforcé ses mécanismes de sécurité depuis, bloquant désormais 99 % des tentatives de contournement recensées, tout en reconnaissant qu'il est « probablement impossible » de concevoir un modèle totalement incontournable. Cet épisode, survenu peu après l'interdiction plus large des modèles Fable 5 et Mythos 5 par l'administration Trump évoquée plus loin dans ce concentré, montre la fragilité persistante des garde-fous des grands modèles de langage face à des utilisateurs déterminés, un enjeu que toute organisation déployant l'IA en production doit continuer de surveiller de près. <a href="/actualites/anthropics-fable-5-is-back-worldwide-after-a-two-week-government-ban-over-a-jailbreak">Approfondir</a>.</p>

<h2 id="7-claude-sonnet-5-arrive-et-sait-naviguer-seul">7. Claude Sonnet 5 arrive et sait naviguer seul</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 1 juillet 2026</p>
<p itemprop="text">Le 1er juillet 2026, <strong>Anthropic</strong> a lancé Claude Sonnet 5, présenté comme son modèle Sonnet le plus autonome à ce jour, capable d'élaborer des plans, d'utiliser un navigateur et un terminal, et d'exécuter des tâches sans supervision constante à un niveau qui exigeait auparavant des modèles plus volumineux et plus coûteux. Le modèle se rapprocherait des performances d'Opus 4.8 tout en étant proposé à <strong>2 $ par million de jetons</strong> en tarif de lancement, valide jusqu'au 31 août 2026. Cette combinaison d'autonomie agentique et de prix réduit vise directement les équipes de développement qui cherchent à automatiser des tâches répétitives de navigation web et de ligne de commande sans multiplier les coûts d'inférence. Pour les développeurs et intégrateurs francophones qui évaluent leur pile d'outils IA, ce positionnement tarifaire agressif mérite d'être comparé aux offres concurrentes avant tout engagement à long terme. <a href="/actualites/claude-sonnet-5-est-la-et-il-sait-utiliser-un-navigateur-et-un-terminal-tout-seul">Source originale</a>.</p>

<h2 id="8-de-vivatech-a-survivatech-lurgence-de-la-souverainete-technologique">8. De VivaTech à SurviTech : l'urgence de la souveraineté technologique</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 29 juin 2026</p>
<p itemprop="text">Le 29 juin 2026, une analyse publiée sur laveille.ai est revenue sur la décision de l'administration Trump d'interdire aux ressortissants étrangers l'accès aux modèles Fable 5 et Mythos 5 d'<strong>Anthropic</strong>, un geste qui met en lumière la dépendance persistante de nombreuses organisations envers des modèles de langage étrangers. Le texte propose le concept de « survivatech », une stratégie où la souveraineté technologique se décline sur trois niveaux distincts : les infrastructures physiques, les systèmes d'IA eux-mêmes, et la valeur économique qui en découle. Plutôt qu'un sujet réservé aux conférences technologiques, l'auteur insiste sur le fait que cette souveraineté doit devenir un critère opérationnel dans les décisions d'approvisionnement. Pour les institutions gouvernementales et parapubliques québécoises qui multiplient les projets d'IA, cette grille de lecture à trois niveaux offre un outil concret pour évaluer leur dépendance réelle envers des fournisseurs étrangers avant de signer un contrat pluriannuel. <a href="/actualites/de-vivatech-a-survivatech">Lecture complète</a>.</p>

<h2 id="9-google-ajoute-des-videos-courtes-a-notebooklm">9. Google ajoute des vidéos courtes à NotebookLM</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 2 juillet 2026</p>
<p itemprop="text">Le 2 juillet 2026, <strong>Google</strong> a introduit dans NotebookLM une fonction de vidéos courtes d'environ <strong>60 secondes</strong>, dans un format qui rappelle les capsules verticales popularisées par TikTok. L'outil analyse le contenu de plusieurs sources déposées par l'utilisateur, qu'il s'agisse de documents, d'articles ou de notes, pour les reformater automatiquement en une capsule vidéo synthétique. La fonctionnalité est offerte dès maintenant aux abonnés Google AI Ultra et Pro, avant un déploiement annoncé prochainement pour les comptes gratuits. Ce format court s'ajoute aux résumés audio de type balado déjà proposés par NotebookLM, renforçant sa position comme outil de synthèse multiformat pour la recherche et l'apprentissage. Pour les enseignants et formateurs qui utilisent déjà NotebookLM pour vulgariser des contenus denses, cette capacité de synthèse vidéo pourrait simplifier la production de capsules pédagogiques courtes sans recourir à un outil de montage distinct. <a href="/actualites/google-brings-tiktok-style-video-shorts-to-notebooklm">Analyse complète</a>.</p>

<h2 id="10-gemini-spark-debarque-sur-mac">10. Gemini Spark débarque sur Mac</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 2 juillet 2026</p>
<p itemprop="text">Le 2 juillet 2026, <strong>Google</strong> a commencé à déployer Gemini Spark, un assistant IA capable d'agir directement sur les fichiers locaux, dans son application Gemini pour Mac. L'outil automatise des tâches complexes comme le tri de documents PDF ou la création de tableaux à partir de fichiers existants, avec un accès aux dossiers locaux strictement contrôlé par l'utilisateur à chaque étape. Cette capacité demeure pour l'instant réservée aux abonnés du forfait <strong>Google AI Ultra à 100 $ par mois</strong> aux États-Unis, un prix qui positionne l'outil dans le segment premium des assistants IA grand public. Le déploiement progressif suggère que Google réserve ses capacités agentiques les plus avancées à ses clients payants les plus engagés, une stratégie de segmentation qui se retrouve désormais chez plusieurs grands fournisseurs d'IA. Pour les utilisateurs individuels et petites équipes d'ici, l'écart de prix avec les forfaits de base mérite d'être soupesé avant adoption. <a href="/actualites/gemini-spark-debarque-sur-mac-votre-portefeuille-risque-de-le-regretter-amerement">Détails sur la fiche</a>.</p>

<h2 id="11-google-reunit-educateurs-et-industrie-pour-penser-lia-en-classe">11. Google réunit éducateurs et industrie pour penser l'IA en classe</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 1 juillet 2026</p>
<p itemprop="text">Le 1er juillet 2026, <strong>Google</strong>, le New York Jobs CEO Council et Urban Assembly ont organisé dans les bureaux de Google un sommet réunissant environ <strong>150 leaders</strong> de l'éducation et de l'industrie pour discuter de l'intégration de l'IA dans les salles de classe et de la préparation des étudiants aux carrières futures. Les échanges ont porté sur des outils comme Google AI Mode et NotebookLM pour renforcer la littératie numérique, tout en insistant sur des compétences humaines jugées irremplaçables comme l'adaptabilité et la collaboration. Les participants ont aussi souligné la nécessité de protéger la vie privée des élèves et d'assurer un accès équitable aux outils d'IA, peu importe le milieu socioéconomique. Pour les acteurs de l'éducation francophone comme École branchée, qui documentent depuis longtemps l'intégration pédagogique du numérique au Québec, ce type de sommet rappelle que la littératie en IA et l'équité d'accès doivent progresser de concert, pas l'une aux dépens de l'autre. <a href="/actualites/new-york-city-educators-and-industry-leaders-gathered-at-googles-offices-to-shape-the-future-of-ai-in-classrooms">Voir le contexte</a>.</p>

<h2 id="12-la-generation-dimages-personnalisees-de-gemini-devient-gratuite">12. La génération d'images personnalisées de Gemini devient gratuite</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 30 juin 2026</p>
<p itemprop="text">Le 30 juin 2026, <strong>Google</strong> a rendu accessible gratuitement à l'ensemble des utilisateurs américains une fonction de génération d'images personnalisées avec Gemini, auparavant réservée à un cercle restreint. La fonctionnalité puise dans les données déjà associées au compte Google de la personne pour produire des illustrations adaptées sans exiger de description détaillée du résultat souhaité. L'activation de l'option « Intelligence personnelle » demeure un préalable obligatoire pour que Gemini puisse accéder à ces informations, ce qui laisse le contrôle du niveau de personnalisation entre les mains de l'utilisateur. Cette gratuité soudaine d'une fonction jusque-là premium illustre la stratégie de Google de démocratiser rapidement certaines capacités d'IA générative dès qu'elles atteignent une maturité suffisante. Pour les responsables de la protection des renseignements personnels dans les organisations d'ici, ce type de fonctionnalité qui combine plusieurs sources de données personnelles mérite un examen attentif avant toute recommandation à des employés. <a href="/actualites/la-generation-dimages-avec-la-memoire-de-gemini-devient-100-gratuite-mais">Décryptage</a>.</p>

<h2 id="13-gmail-live-veut-retrouver-vos-courriels-a-votre-place">13. Gmail Live veut retrouver vos courriels à votre place</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 30 juin 2026</p>
<p itemprop="text">Le 30 juin 2026, <strong>Google</strong> a présenté Gmail Live, une fonctionnalité annoncée lors de Google I/O 2026 qui permet de rechercher des courriels par commande vocale directement depuis l'application mobile, en transformant la recherche en une conversation plutôt qu'en une suite de mots-clés. L'outil affiche des suggestions de requêtes pour guider l'utilisateur et demeure actuellement en phase de test auprès d'un nombre restreint de personnes. Le déploiement initial ciblera les abonnés payants Google AI Pro et Ultra au cours de l'été 2026, avant une extension prévue vers d'autres produits comme Google Docs et Google Keep. Cette approche conversationnelle de la recherche s'inscrit dans une tendance plus large où les grands fournisseurs remplacent progressivement les champs de recherche traditionnels par des interfaces vocales ou en langage naturel. Pour les entreprises d'ici qui gèrent un grand volume de correspondance, l'arrivée éventuelle de cette fonction en français sera à surveiller de près. <a href="/actualites/marre-de-chercher-vos-courriels-gmail-live-veut-les-retrouver-a-votre-place">Approfondir</a>.</p>

<h2 id="14-google-meet-laisse-gemini-prendre-les-notes">14. Google Meet laisse Gemini prendre les notes</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 29 juin 2026</p>
<p itemprop="text">Le 29 juin 2026, <strong>Google</strong> a annoncé que Google Meet s'appuie désormais sur Gemini pour prendre des notes automatiquement pendant les appels, en écoutant les échanges en temps réel afin de générer un compte rendu structuré et d'identifier les actions à mener par les participants. Un récapitulatif est ensuite envoyé automatiquement par courriel une fois la réunion terminée, ce qui évite qu'un participant doive jouer le rôle de preneur de notes. La fonction demeure réservée aux abonnés des forfaits Google AI Pro et Ultra, cohérent avec la stratégie de Google de réserver ses capacités agentiques les plus utiles aux clients payants. Pour les organisations d'ici qui tiennent de nombreuses réunions virtuelles, cette automatisation soulève une question de gouvernance simple mais essentielle : qui doit consentir à ce que l'IA analyse le contenu d'un appel, et où ces transcriptions sont-elles conservées une fois générées. <a href="/actualites/google-meet-laisse-maintenant-gemini-prendre-des-notes-a-votre-place-pendant-vos-appels">Source originale</a>.</p>

<h2 id="15-renault-integre-gemini-dans-ses-vehicules">15. Renault intègre Gemini dans ses véhicules</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 29 juin 2026</p>
<p itemprop="text">Le 29 juin 2026, <strong>Renault</strong> a annoncé l'intégration de Gemini, l'IA de Google, dans son système embarqué openR Link, dans le but d'améliorer les interactions vocales avec le véhicule. Le système comprend désormais des requêtes formulées en langage naturel et combine recherche web et exécution d'actions concrètes dans la voiture, comme régler la température ou trouver un point d'intérêt, en une seule commande. Le déploiement se fera par mise à jour à distance sur des modèles déjà en circulation, sans nécessiter de passage en concession, et les conducteurs conservent la possibilité de désactiver l'assistant. Cette intégration illustre la diffusion rapide des grands modèles de langage bien au-delà des applications de bureau, jusque dans l'habitacle automobile. Pour le secteur manufacturier lié à l'industrie automobile d'ici, ce type de partenariat entre constructeur et fournisseur d'IA générative confirme que l'expérience conducteur devient un terrain de différenciation à part entière. <a href="/actualites/renault-accueille-gemini-votre-voiture-comprend-maintenant-mieux-ce-que-vous-lui-dites">Lecture complète</a>.</p>

<h2 id="16-un-entrepreneur-indien-investit-30-m-dans-une-alternative-a-microsoft-office">16. Un entrepreneur indien investit 30 M$ dans une alternative à Microsoft Office</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 2 juillet 2026</p>
<p itemprop="text">Le 2 juillet 2026, l'entrepreneur indien <strong>Bhavin Turakhia</strong>, cofondateur de Zeta, a annoncé investir <strong>30 millions de dollars</strong> de ses propres fonds dans Neo, une plateforme de travail pensée dès sa conception autour de l'IA plutôt que d'y greffer des fonctions après coup. Neo combine gestion de projets, documents et stockage en un seul produit, se voulant agnostique quant aux modèles d'IA utilisés en arrière-plan. Turakhia justifie son approche en affirmant qu'on ne peut pas transformer les pièces d'un vieux téléphone Nokia en iPhone : selon lui, les suites bureautiques préexistantes ne peuvent être simplement rafistolées avec de l'IA. Neo prévoit d'embaucher une centaine d'employés d'ici la fin de l'année, dont une majorité d'ingénieurs, avant un lancement ciblant les petites et moyennes entreprises. Pour les PME québécoises qui envisagent de remplacer leur suite bureautique classique, cette nouvelle venue s'ajoute à une liste croissante d'options pensées nativement pour l'IA, à évaluer face aux outils déjà bien ancrés comme Microsoft 365. <a href="/actualites/indian-tech-tycoon-bets-30m-of-his-own-money-to-build-ai-alternative-to-microsoft-office">Analyse complète</a>.</p>

<h2 id="17-mistral-publie-leanstral-15-specialiste-de-la-preuve-formelle">17. Mistral publie Leanstral 1.5, spécialiste de la preuve formelle</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 4 juillet 2026</p>
<p itemprop="text">Le 4 juillet 2026, <strong>Mistral AI</strong> a publié Leanstral 1.5, un modèle open source distribué sous licence Apache 2.0 et conçu spécifiquement pour la vérification formelle dans le langage Lean 4, plutôt que comme assistant conversationnel généraliste. Le modèle atteint <strong>100 %</strong> sur le benchmark mathématique miniF2F, un résultat qui sature essentiellement cette évaluation de référence, et résout 587 des 672 problèmes du benchmark PutnamBench. Au-delà des mathématiques pures, Leanstral 1.5 sert aussi d'agent de vérification sur du code réel : dans un pipeline de conversion de Rust vers Lean, il a détecté plusieurs bogues auparavant inconnus dans des dépôts open source, dont un dépassement de capacité entière non répertorié. Les poids du modèle sont hébergés sur Hugging Face avec un point d'accès API gratuit chez Mistral. Pour les équipes de génie logiciel qui travaillent sur des systèmes critiques d'ici, un outil de vérification formelle ouvert et gratuit pourrait réduire le coût d'entrée vers des pratiques de preuve encore peu répandues hors des cercles académiques. <a href="/actualites/mistrals-open-source-leanstral-15-aces-formal-math-benchmarks-and-catches-real-bugs-in-code">Détails sur la fiche</a>.</p>

<h2 id="18-des-elus-americains-veulent-interdire-la-vente-de-donnees-de-sante-liees-a-lia">18. Des élus américains veulent interdire la vente de données de santé liées à l'IA</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 29 juin 2026</p>
<p itemprop="text">Le 29 juin 2026, les élus américains <strong>Elizabeth Warren</strong> et Mary Gay Scanlon ont annoncé une nouvelle proposition de loi visant à interdire la vente de données de santé et de localisation à des courtiers en données, une protection qui couvrirait explicitement les informations partagées avec des agents conversationnels comme ChatGPT ou Claude. Le texte est présenté comme une mise à jour du Health and Location Data Protection Act, adaptée spécifiquement à l'ère des systèmes d'IA conversationnels qui recueillent des confidences de nature médicale sans le cadre réglementaire strict qui encadre les dossiers de santé traditionnels. Pour les organisations québécoises, cette initiative américaine résonne avec les obligations déjà en vigueur ici sous la Loi 25, qui impose son propre régime de consentement et de protection des renseignements personnels, y compris sensibles, échangés avec des outils d'IA générative. Cette proposition rappelle qu'aux États-Unis aussi, l'absence de garde-fous spécifiques aux chatbots inquiète les élus, un décalage que le Québec a en partie déjà comblé. <a href="/actualites/lawmakers-want-to-ban-ai-companies-from-selling-your-health-data">Voir le contexte</a>.</p>

<h2 id="19-des-ecoles-privees-misent-sur-lia-pour-seduire-les-familles-aisees">19. Des écoles privées misent sur l'IA pour séduire les familles aisées</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 5 juillet 2026</p>
<p itemprop="text">Le 5 juillet 2026, un reportage a documenté l'essor des écoles privées américaines qui misent sur l'IA pour personnaliser l'apprentissage, à l'image d'Alpha School, où les élèves suivent environ deux heures de tutorat individualisé par IA avant de passer à des ateliers pratiques. La scolarité y coûte jusqu'à <strong>75 000 $</strong> par année selon les campus, un modèle qui attire des familles fortunées prêtes à payer une prime pour un encadrement individualisé assisté par IA. Le réseau a ouvert huit nouveaux campus en 2025, notamment à San Francisco et à New York, et prévoit de poursuivre son expansion. Le reportage évoque aussi une statistique préoccupante, à confirmer par d'autres sources : une proportion importante des utilisateurs à long terme de l'IA rapporteraient avoir délégué une partie de leur réflexion à l'outil plutôt que de la faire eux-mêmes. Pour les décideurs en éducation d'ici, ce modèle soulève une question d'équité simple : au prix demandé, l'apprentissage personnalisé par IA reste hors de portée de la majorité des familles québécoises. <a href="/actualites/ai-private-schools-sell-wealthy-us-families-on-personalized-learning-over-traditional-education">Décryptage</a>.</p>

<h2 id="20-midjourney-somme-hollywood-de-reveler-son-usage-interne-de-lia">20. Midjourney somme Hollywood de révéler son usage interne de l'IA</h2>
<p style="color:#475569;font-size:0.9rem;font-style:italic;margin:0 0 8px;">Publié le 4 juillet 2026</p>
<p itemprop="text">Le 4 juillet 2026, la startup <strong>Midjourney</strong>, poursuivie séparément par Disney, Universal et Warner Bros. pour violation de droits d'auteur, a demandé aux studios de révéler dans le cadre du litige les détails de leur propre usage interne de l'IA, notamment pour le storyboard. L'entreprise soutient qu'exploiter des images protégées pour l'entraînement de ses modèles relève de l'usage équitable (fair use) et affirme que les studios eux-mêmes recourent à des pratiques similaires en coulisses, ce qu'ils chercheraient précisément à garder confidentiel. Disney et Universal avaient intenté leur poursuite en 2023, suivis quelques mois plus tard par Warner Bros., dans l'un des dossiers les plus surveillés de l'industrie du divertissement sur la propriété intellectuelle et l'IA générative. Pour les créateurs et studios de production d'ici qui utilisent déjà des outils d'IA générative dans leur propre flux de travail, ce bras de fer juridique illustre à quel point la frontière entre usage interne toléré et usage commercial contesté demeure floue tant qu'aucun tribunal n'a tranché. <a href="/actualites/midjourney-wants-hollywood-studios-to-reveal-the-details-of-their-ai-usage">Approfondir</a>.</p>
HTML;

        $categoryId = Category::find(6)?->id
            ?? Category::whereJsonContains('slug->fr_CA', 'concentre')
                ->orWhereJsonContains('slug->fr_CA', 'le-concentre')
                ->first()?->id;

        $author = User::where('email', 'stephane@memora.ca')->first()
            ?? User::where('name', 'like', '%Stephane Lapointe%')->first()
            ?? User::where('name', 'like', '%Stéphane Lapointe%')->first();

        Article::create([
            'title' => ['fr_CA' => $title, 'fr' => $title],
            'slug' => ['fr_CA' => $slug, 'fr' => $slug],
            'content' => ['fr_CA' => $content, 'fr' => $content],
            'excerpt' => ['fr_CA' => $excerpt, 'fr' => $excerpt],
            'featured_image' => 'images/blog/concentre-hebdo-2026-06-29-au-2026-07-05.jpg',
            'status' => PublishedArticleState::class,
            'published_at' => \Carbon\Carbon::now('America/Toronto')->subMinutes(5),
            'category_id' => $categoryId,
            'is_featured' => true,
            'user_id' => $author?->id ?? 1,
            'meta' => [
                'seo_title' => $seoTitle,
                'meta_description' => $metaDescription,
            ],
            'tags' => ['concentré', 'hebdo', 'veille-ia', 'actualités', 'quebec', 'ia-2026'],
        ]);

        $this->command?->info('Article Concentré hebdo 29 juin au 5 juillet 2026 créé.');
    }
}
